### ISSUE TITLE
How to set permissions to not conflict between Web server and app server

### ISSUE THREAD

**Issue by paulmenzel** [phusion/passenger-docker#102]
NGINX runs under the user `www-data` and the app under the user `app`.

Assume there are files in `public/my-uploads/some-hash/receipt-for-customer-X.pdf`

    -rw-r-----  1 app app  x Apr 15  2014 public/my-uploads/some-hash/receipt-for-customer-X.pdf

which shouldn’t be world readable.

Now the problem is, that the file cannot be served by NGINX, as this runs as user `www-data` and cannot read that file.

How should that problem be solved? Add `www-data` to the group `app`?

**Comment by FooBarWidget** [comment]
Yes that last method is one way to solve the problem.

This is not really a Passenger problem; it's more a general Unix system question.
