### ISSUE TITLE
Is sub-URI use-cases possible with passenger-docker

### ISSUE THREAD

**Issue by mech** [phusion/passenger-docker#103]
Let's say I have to serve 2 URL like

```
http://host.com/
http://host.com/eva
```

With normal passenger, I can use sub-URI approach with `passenger_base_uri` approach. With the Docker situation, I am abit confuse which model should I use to deploy multiple applications within a single container. Should I use a reverse proxy approach for sub-URI use-case?

Does that mean I need to have 3 containers. 1 to act as reverse proxy and the other 2 for each of the applications?

How does 1 approach the issues of sub-URI in a containerized world of passenger?

**Comment by FooBarWidget** [comment]
passenger-docker uses the Nginx integration mode. Thus, you can just follow the sub-URI deployment documentation for the Nginx integration mode: https://www.phusionpassenger.com/library/deploy/nginx/deploy/ruby/#deploying-an-app-to-a-sub-uri
