### ISSUE TITLE
Nodejs version too high for Meteor in passenger-nodejs

### ISSUE THREAD

**Issue by ShaunEgan** [phusion/passenger-docker#105]
`passenger-nodejs` image uses node version `0.12.7` where Meteor only officially supports `0.10.36`

From my experiments, it breaks at least the simple mail functionality built into the auth package for Meteor. Using `n` to install and use `0.10.36` causes the error to go away.

If I am not being silly, maybe there should be a `passenger-meteorjs` image which uses the older version of node instead of this approach?

**Comment by FooBarWidget** [comment]
Yes, it sounds like it would be a good idea. I don't suppose Meteor plans on supporting Node.js 0.12 any time soon?

**Comment by VanguardZA** [comment]
Can't see anything regarding timelines or even intent.
