### ISSUE TITLE
Deployment walk-through please

### ISSUE THREAD

**Issue by danja** [phusion/passenger-docker#107]
### Request
It would be very helpful to have a short page of minimal documentation, aimed at a total newbie. It should describe, from scratch, how to get passenger-docker up and running on a production machine.

For comparable ref, see e.g. https://www.codeschool.com/blog/2015/01/16/production-deployment-docker/

### Reason
The (very convincing) video says it's possible to simplify production deployment. But for a docker newbie, it isn't clear where to start, what's actually essential , basically how to do it...

https://vimeo.com/phusionnl/review/84945384/73fe7432ee

*I want to dev/deploy some fairly complex node.js webapps on a remote Ubuntu machine. I'm currently doing everything manually, no VM, no Docker, containers, nothing... Just passing material across with git. Docker/passenger looks a promising way forward for dev/deployment*

**Comment by FooBarWidget** [comment]
We have a full end-to-end deployment walkthrough in the official Passenger documentation website: https://www.phusionpassenger.com/library/walkthroughs/deploy/nodejs/
It covers everything from launching a server, to installing Node.js, to installing Passenger, to configuring Nginx, to automating deployments.

However, the walkthrough assumes you follow it on a new, clean system.

The walkthrough also does not teach you how to do all this in combination with Docker. If you are just starting out, then I do not recommend using Docker at all. Docker operates at a level of abstraction that only makes sense if you are *already* experienced with system administration. For example, building a Docker container requires that you already know how the command line works, that you already understand which commands are necessary and why they are necessary, that you understand the Unix process model and hierarchy structure, etc. I recommend becoming adept at "regular" system administration first before even looking at anything Docker-related.

**Comment by danja** [comment]
Thanks for the link, I wasn't aware of Passenger outside of Docker.

But it is specifically the Docker deployment I'm interested in. I've already got scripts in place for node.js deployment, it's just all rather ad hoc & fragile. docker-passenger looks a good way of making it more systematic & robust, only the docs at the moment are rather impenetrable.

(btw, I do have some system admin experience: years back I configured & maintained the network for a whole UK college, staff & students; have about 20 years experience on *nix systems, maybe 15 on web dev, been on various specification working groups; have contributed to 10 books on the subject; spent a few years with node... but am new to Docker :)

**Comment by tinco** [comment]
Hi,

passenger-docker is a docker image, so you can use the docker tutorials to
understand how it works:

https://docs.docker.com/linux/started/

Kind regards,
Tinco

On Fri, Sep 11, 2015 at 7:41 PM, Danny Ayers <notifications@github.com>
wrote:

> Thanks for the link, I wasn't aware of Passenger outside of Docker.
>
> But it is specifically the Docker deployment I'm interested in. I've
> already got scripts in place for node.js deployment, it's just all rather
> ad hoc & fragile. docker-passenger looks a good way of making it more
> systematic & robust, only the docs at the moment are rather impenetrable.
>
> (btw, I do have some system admin experience: years back I configured &
> maintained the network for a whole UK college, staff & students; have about
> 20 years experience on *nix systems, maybe 15 on web dev, been on various
> specification working groups; have contributed to 10 books on the subject;
> spent a few years with node... but am new to Docker :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phusion/passenger-docker/issues/107#issuecomment-139609928>
> .
>



-- 
Phusion B.V. | Web Application deployment, scaling, and monitoring solutions

Web: http://www.phusion.nl/
E-mail: info@phusion.nl
Chamber of commerce no: 63501007 (The Netherlands)
