### ISSUE TITLE
Multitenancy with Meteor

### ISSUE THREAD

**Issue by Svenskunganka** [phusion/passenger-docker#108]
Hi!

I am currently using Passenger to run my Meteor apps, but I do not use `passenger-docker` to run them. I'm in the process of setting up a better workflow with CI using GitLab CI specifically which works really well with Docker - hence why I'm really happy that something like `passenger-docker` exists.

Something that I'm curious about is how would I handle multiple Meteor applications under different domains with `passenger-docker` in production? There's the `-p` option for docker, but I can't bind multiple containers to the same host port, e.g `-p 80:80` for every contained application that I run, and I'm pretty sure that wouldn't work either. In all scenarios I've thought of the host would require an nginx process that proxies incoming requests to the containers based on `server_name` which in turn has a nginx process with passenger handling the Meteor app.  
The whole workflow would look something like this:
![Workflow](http://i.imgur.com/l0yjxM2.png)

In a way I really feel like this is a bad setup, to have one nginx process in front of a container with another nginx process, but I can't see any other solution. I'm currently building an application that I feel can recieve a bit of traffic, so I want to be prepared to scale if needed so I'm looking into CoreOS as a solution and the only problem I can see is that best practices with CoreOS is that containers are the packages from the package manager, so the host CoreOS shouldn't run an Nginx proxy.

I could however spin up another container serving as the Nginx proxy equivalent of the host which handles load blancing and proxying to the other containers.

Anyhow, would be much appreciated if anyone with experience with this kind of setup can shed some light on the matter!

Cheers!

**Comment by FooBarWidget** [comment]
Putting nginx in front of your other containers is the corrrct solution. I
would not worry about overhead if i were you. If you need to scale, nginx
is about the last component to worry about.
