### ISSUE TITLE
Forwarding Nginx logs to docker

### ISSUE THREAD

**Issue by kswope** [phusion/passenger-docker#111]
I see that the crond is running and logrotate is set up to rotate the nginx logs and thats all good but in a container shouldn't the logging be redirected to stdout and stderror?

I'm using the 12factor gem to redirect rails logs to stdout and stderr but what about the nginx logs?

I'm not sure but I think nginx also logs stderr of a subprocess to error.log

This is all very confusing and I think there should be some info about it in the README

I'm also trying this, any better ideas?

```
RUN ln -sf /dev/stdout /var/log/nginx/access.log                                                                                                
RUN ln -sf /dev/stderr /var/log/nginx/error.log 
```

[EDIT]

There's also http://nginx.org/en/docs/ngx_core_module.html#error_log but I'm not seeing anything for access logs.

**Comment by kswope** [comment]
Ahah below forwards the nginx logs to docker and is already enabled, thanks!

But what about access logs?  There is definitely nothing forwarding them to docker, and removing access_log from nging.conf doesn't cause it to start writing to stdout.  All I've got so far is 
ln -sf /dev/stdout /var/log/nginx/access.log                                                                                                



rails_12factor takes care of rails logging to docker because it outputs to stdout



```
> more /etc/service/nginx-log-forwarder/run 

#!/bin/bash
# Forwards the Nginx error.log to the Docker logs.
set -e
if [[ -e /var/log/nginx/error.log ]]; then
        exec tail -F /var/log/nginx/error.log
else
        exec sleep 10
fi
```

**Comment by FooBarWidget** [comment]
Access logs aren't being forwarded right now. Maybe we should do that in the next version.

**Comment by shaneog** [comment]
I'd also like to see a recommended access logging strategy

**Comment by anlek** [comment]
I'd like to know how to stop nginx access log forwarding (in development)

**Comment by jeffbyrnes** [comment]
Myself and @andrhamm are running into an issue where, with the logging set up like so:

```ruby
config.logger = ::Logger.new(STDOUT)

# Use default logging formatter so that PID and timestamp are not suppressed.
config.log_formatter = ::Logger::Formatter.new
```

We end up with log messages like so:

```
App 172 stdout: I, [2016-07-08T14:19:35.607941 #172]  INFO -- Status: 200
```

That `App 172 stdout:` bit is being appended, and we do not want it. Where is it coming from? Passenger? Docker?

**Comment by FooBarWidget** [comment]
@jeffbyrnes It's coming from Passenger. This is currently non-configurable.

**Comment by jeffbyrnes** [comment]
@FooBarWidget thanks for confirming that.

**Comment by shaneog** [comment]
@FooBarWidget Is this logging (`App X stdout:`) still non-configurable? 
My app logs in JSON and the Docker logs are picked up by logstash. This output breaks my logging environment.
I am using Passenger Standalone in Docker.

**Comment by OnixGH** [comment]
For questions / remarks about Passenger features please refer to the [Passenger community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) or the [Passenger issue list](https://github.com/phusion/passenger/issues).

The original question about log forwarding is answered, and I've split the enhancement request for access logging to https://github.com/phusion/passenger-docker/issues/189.
