### ISSUE TITLE
nginx log rotation doesn't work

### ISSUE THREAD

**Issue by steti** [phusion/passenger-docker#113]
Log rotation for `/var/log/nginx/access.log` and `/var/log/nginx/error.log` seems to be broken.  After 1 day, the log files are moved to `access.log.1` and `error.log.1` but nginx continues to write to those files rather than the new ones.

This seems to be a similar issue to https://github.com/phusion/baseimage-docker/issues/167 which was fixed here: https://github.com/phusion/baseimage-docker/commit/9b08ea9cd4ef554c7127130795dd515d2988064b

**Comment by cjroebuck** [comment]
+1 seeing this too

**Comment by Wedontplay** [comment]
+1 Same problem. 
There is already a PR for this, can someone merge it?

**Comment by JonKernPA** [comment]
+1

**Comment by ian-walther** [comment]
+1

**Comment by JonKernPA** [comment]
Do I really have to restart my server every week because of this log rotate error?
Can a maintainer merge it, please?

**Comment by shingara** [comment]
Move the access log in STDOUT. I do it in my own fork and avoid this kind of issue

**Comment by FooBarWidget** [comment]
This has been fixed now. Sorry for the delay.
