### ISSUE TITLE
Doesn't work with meteor's 1.2 websocket compression

### ISSUE THREAD

**Issue by rbabayoff** [phusion/passenger-docker#117]
Hey,

The latest version of meteor, 1.2, introduced websocket compression that is enabled by default. See [here](https://github.com/meteor/meteor/blob/devel/History.md). It doesn't work with passenger docker and nginx. 

I was able to get it to work by disabling meteor's web socket compression (set the SERVER_WEBSOCKET_COMPRESSION environment variable to 0).

I wondered if the passenger or nginx config can be modified to support web socket compression with meteor. I can quickly try it out, if given guidance.

**Comment by rbabayoff** [comment]
Clarification - it works for me locally (on same computer), but when I deploy my app to digital ocean, it doesn't work and disabling it fixes it. Any clues?

**Comment by rhyslbw** [comment]
Also curious about this

**Comment by OnixGH** [comment]
This tracker is for issues specifically concerning the containerization of Passenger (not its features).

The best place to get info or help is on the [forum](https://groups.google.com/forum/#!forum/phusion-passenger) or the [Passenger issue tracker](https://github.com/phusion/passenger).
