### ISSUE TITLE
Ruby-22 does not connect to postgres

### ISSUE THREAD

**Issue by dhf0820** [phusion/passenger-docker#118]
Odd situation. Running two containers one with the rails app and one for postgres.  Both start up.  Connect to the we container with docker exec and I can run rake to migrate the tables and seed the DB. I can run rails c and access the data.  I can also access the db from the web using docker-compose run web db:create and it creates the DB on the server. 

When I attempt to access the url I get an error.

App 146 stdout: PG::ConnectionBad (could not connect to server: No such file or directory
App 146 stdout: 	Is the server running locally and accepting
App 146 stdout: 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

I am not a PG expert however why would a container with out the PG runtime be looking at a socket?  I can access the DB container outside through various tools including psql. 

I am at a loss to figure out why works 

Don French

**Comment by dhf0820** [comment]
I can run the same rails app on a system without postgres and it works fine

**Comment by FooBarWidget** [comment]
I think a PostgreSQL expert may be better able to help you. This doesn't look like a passenger-docker problem to me.

**Comment by bennick** [comment]
@dhf0820 Are you lining your containers correctly? 

https://docs.docker.com/userguide/dockerlinks/

**Comment by jayapriyam** [comment]
sudo postgresql restart
