### ISSUE TITLE
Update ruby22 to 2.2.3

### ISSUE THREAD

**Issue by ka2n** [phusion/passenger-docker#119]
Brightbox APT's Ruby 2.2 variant has been updated to 2.2.3 since August 2015.
It's just rebuild and release new image. Thanks.

**Comment by antoinefinkelstein** [comment]
:+1: Indeed, an update would be great

**Comment by hamid-elaosta** [comment]
Would love to see a 2.2.3 version on Docker Hub. It is after all a security fix.

**Comment by shaneog** [comment]
Agreed. Waiting for this

**Comment by FooBarWidget** [comment]
Looks like there is a libxml security patch and an OpenSSL security patch too. I'll try to find time next week to do everything in one go. In the mean time, you can do this yourself by adding a simple 'apt-get update && apt-get upgrade' command in your dockerfile.

**Comment by shaneog** [comment]
Thanks @FooBarWidget

**Comment by OnixGH** [comment]
Obsoleted by #124
