### ISSUE TITLE
Update ruby22 to 2.2.4

### ISSUE THREAD

**Issue by ain** [phusion/passenger-docker#124]
Considering [another security fix](https://www.ruby-lang.org/en/news/2015/12/16/ruby-2-2-4-released/) that landed in `2.2.4`, we should go up in version.

This ticket should obsolete #119.

**Comment by hamid-elaosta** [comment]
+1 for security fixes. Come on Phusion, speed up this update process. Pretty please.

**Comment by FooBarWidget** [comment]
You don't need to wait for us to apply security updates. Just run `apt-get update && apt-get upgrade`.

**Comment by hamid-elaosta** [comment]
I'm aware, it was mentioned in #119 I believe. It's nice to have a specific version you can target though when deploying. Apt upgrades could get you any version.

**Comment by OnixGH** [comment]
@hamid-elaosta You can use apt pinning if you're worried about versions.

**Comment by hamid-elaosta** [comment]
@OnixGH Yes, of course. I think this is how I will move forward. Thanks for the input.

**Comment by jeffnappi** [comment]
ETA on this?

**Comment by FooBarWidget** [comment]
Sorry for the delay. This has been implemented in 0.9.19, to be released today.
