### ISSUE TITLE
memcached and redis should listen on all interfaces

### ISSUE THREAD

**Issue by scottjacobsen** [phusion/passenger-docker#126]
Redis and memcached are configured to listen on localhost only. In order to use this image for a redis or memcached server the conf files need to replaced in my Dockerfile.

Given that docker containers don't accept connections unless ports are explicitly opened I can't see any benefit to this.

Shouldn't memcached and redis listen on all interfaces?

**Comment by OnixGH** [comment]
The reason that memcached and redis listen on localhost is that in this image they are intended to be used only by the application in the same container. If you want a shared memcached and/or redis, it would make more sense to use dedicated image(s) for that.

Btw. this is not entirely correct:
> Given that docker containers don't accept connections unless ports are explicitly opened I can't see any benefit to this.

If you don't bind to localhost then everything running on the host itself (e.g. host processes and other containers) will be able to connect, regardless of what you do with `EXPOSE` and `-p`.
