### ISSUE TITLE
environment vars not getting down to rails 

### ISSUE THREAD

**Issue by sburke56** [phusion/passenger-docker#128]
I am trying to consolidate my environment var declarations to one place so I can keep them out of my repo easier.  I modeled my setup after the [Setting environment vars in Nginx](https://github.com/phusion/passenger-docker#setting-environment-variables-in-nginx) section. 

Docker file 
```
ENV GDE_SECRET_KEY_BASE=${GDE_SECRET_KEY_BASE}
ADD config/docker/staging/env.conf /etc/nginx/main.d/env_stage.conf
```

env.conf file 
```
env GDE_SECRET_KEY_BASE;
```

So this doesn't seem to work?  The way the docs read is that the env.conf file placed in /etc/nginx/main.d is a whitelist of environment vars to allow through.  Is this correct?  The only way I was able to get things running is if I define the environment vars in the env.conf file.  What am I missing here?

**Comment by krsyoung** [comment]
@sburke56 did you ever have luck with this?  I have a similar set-up working with my environment (although I'm passing my environment variables through `docker-compose.yml` which I would think should be doing the same as the ENV directive you have.  If you run a container explicitly calling --env GDE_SECRET_KEY_BASE=1234...  does that work?

**Comment by sburke56** [comment]
Not really no. I still have to define the environment vars in the env.conf file and that gets added to the correct directory with the ADD in the dockerfile. 

In order to keep things out of my repo I added a step in my build that would check out the env.conf.skel file and search replace with sed for the values I needed in there and create the env.conf file when I build my container.
