### ISSUE TITLE
Installed Ruby version is not set as default

### ISSUE THREAD

**Issue by janpapenbrock** [phusion/passenger-docker#129]
Using this Dockerfile based on the customizable image:

```
FROM phusion/passenger-customizable:0.9.18

RUN /pd_build/ruby2.1.sh
RUN ruby --version
```

Prints when built:

```
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]
```

However, I _expected_ it to set Ruby 2.1 as default. It can be made to work with an additional line in Dockerfile:

```
RUN ruby-switch --set ruby2.1
```

Prints when built:

```
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux-gnu]
```

I could imagine two ways to solve this:  
1. In each `/pd_build/rubyX.X.sh` script, call `ruby-switch` with the appropriate version after `ruby-finalize.sh` 
2. Modify `ruby-finalize.sh` to determine the version via ENV or something

**Comment by FooBarWidget** [comment]
This is how it is supposed to work. The latest installed version is set as default. If you do not want this then you have to explicitly set custom default.
