### ISSUE TITLE
Change redis repo

### ISSUE THREAD

**Issue by rwky** [phusion/passenger-docker#130]
I don't support my redis repo any more (I don't use it and don't have the time any more :cry: ) so the repo should be switched, I suggest using https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server

I may make a PR for this if I get time.

**Comment by FooBarWidget** [comment]
Thanks for the heads-up. This has been fixed in 0.9.19, which installs Redis from the Ubuntu repository.
