### ISSUE TITLE
502 Gateway Timeout

### ISSUE THREAD

**Issue by karthiknamburu** [phusion/passenger-docker#131]
Hi,
For our rails application using the passenger image we are observing a request timeout's for a search form(approximately 3 minutes).By checking the logs it seems one of the passenger instance is being killed during the request.

Im using ruby 2.2.2  and Rails 4.1.14

Error form the log.

[ 2016-02-08 00:37:26.2168 9/7f27bdfef700 age/Cor/Con/InternalUtils.cpp:105 ]: [Client 1-371] Sending 502 response: application did not send a complete response
192.168.99.1 - - [08/Feb/2016:00:37:26 -0500] "POST /searches HTTP/1.1" 502 54 "http://192.168.99.102/searches" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
[ 2016-02-08 00:37:29.0203 9/7f27c47bc700 age/Cor/App/Poo/AnalyticsCollection.cpp:105 ]: Process (pid=147, group=/home/webapp/public (development)) no longer exists! Detaching it from the pool.
[ 2016-02-08 00:37:29.0204 9/7f27c47bc700 age/Cor/CoreMain.cpp:794 ]: Checking whether to disconnect long-running connections for process 147, application /home/webapp/public (development)

can you please help me on the timeout issue.

thanks in advance.

**Comment by michaeloboyle** [comment]
Could this be related to this issue?
**Application crashes with uninitialized Rack constant when run in Passenger** [#1478](https://github.com/phusion/passenger/issues/1478)

**Comment by FooBarWidget** [comment]
That just looks like the app randomly crashed without printing an error message.
