### ISSUE TITLE
Permission denied @ rb_sysopen - log/production.log (Errno::EACCESS)

### ISSUE THREAD

**Issue by przbadu** [phusion/passenger-docker#143]
hey guys, everything was working perfect, until I used the latest version of passenger-docker image `phusion/passenger-ruby22:0.9.19` which now is using `rvm` to manage ruby versions.

When I deploy my app, I keep getting permission issues for `logs` and `tmp` directories. And I have to manually give permission to `log/*.log`. Here is my Dockerfile, please suggest me easiest way to permit all files inside `tmp/` and `log/` directory:

      FROM phusion/passenger-ruby22:0.9.19
      MAINTAINER przbadu "przbadu@example.com"

      # set correct environment variables
      ENV HOME /root
      ENV RAILS_ENV production

      # Use baseimage-docker's init system.
      CMD ["/sbin/my_init"]

      # Expose Nginx HTTP service
      EXPOSE 80

      # Start Nginx / Passenger
      RUN rm -f /etc/service/nginx/down

      # Remove the default site
      RUN rm /etc/nginx/sites-enabled/default

      # Add the nginx site and config
      ADD nginx.conf /etc/nginx/sites-enabled/nginx.conf
      ADD rails-env.conf /etc/nginx/main.d/rails-env.conf

      # Let ensure these packages are already installed
      # otherwise install them anyways
      RUN apt-get update && apt-get install -y build-essential \
                                               nodejs \
                                               libpq-dev

      # bundle gem and cache them
      WORKDIR /tmp
      ADD Gemfile /tmp/
      ADD Gemfile.lock /tmp/
      RUN gem install bundler
      RUN bundle install

      # Add rails app
      ADD . /home/app/webapp
      WORKDIR /home/app/webapp

      # NOTE: workaround but I didn't liked this approach
      RUN touch log/production.log log/logentries.log log/another.log 

      RUN chown -R app:app /home/app/webapp
      RUN RAILS_ENV=production rake assets:precompile

      # Clean up APT and bundler when done.
      RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

I tried giving `chmod -R 775 log/` but that didn't worked

**Comment by przbadu** [comment]
Running docker image and checking `whoami` gives me `root`, so I remove this line from above `Dockerfile` and still same issue:

   - Run chown -R app:app /home/app/webapp

**Comment by przbadu** [comment]
For more information: https://github.com/phusion/passenger-docker/issues/110

__PROBLEM__: `RUN RAILS_ENV=production rake assets:precompile` was changing whole permission things for `log` directory.

_FIX_ is:

`RUN setuser app rake assets:precompile RAILS_ENV=production`

run any rake commands in `Dockerfile` as `app` user, passenger docker image has `setuser` command, You can think `setuser app` as `sudo -u app`.

Thanks, hope this will help someone.

**Comment by przbadu** [comment]
You can also try reordering these lines, I haven't tested it but I think this should work:

```docker
  RUN RAILS_ENV=production rake assets:precompile
  RUN chown -R app:app /home/app/webapp
```

The idea is, add `chown` after all rake commands are executed, so that it will bring ownership to previous state.

**Comment by Xuhao** [comment]
@przbadu Thanks a lot for your solutiona, you saved me!

**Comment by skunkworker** [comment]
I'm on docker `17.09.1-ce-mac42 (21090)` on my mac and while the `RUN chown -R app:app /home/app/webapp` works it takes a long time (about 45 seconds). Is there any way around that problem? And I am using `FROM phusion/passenger-ruby24:0.9.27`
