### ISSUE TITLE
Nginx taking a long time to kill workers (WINCH)

### ISSUE THREAD

**Issue by derosm2** [phusion/passenger-docker#144]
As part of our deployment process we use gantryd to reroute traffic from the old container to a new container. During this process we send WINCH to the Nginx master process (http://nginx.org/en/docs/control.html) to gracefully shut down the workers before we remove the old container. 

This process usually took just a 2-3 minutes, but since the new version of the passenger-docker image we're seeing it take up to 45 minutes in some cases and not less than 7-8 minutes.

I know this new release updated a lot of pieces, but any suggestions or advice would be much appreciated.

**Comment by OnixGH** [comment]
@derosm2 did you try with 0.9.21?

Either way we'd need more info to act on, like what exactly is taking extra time (e.g. what does passenger-status show during the shutdown).

**Comment by derosm2** [comment]
@OnixGH We changed our deployment process so that we don't send WINCH anymore. We now take advantage of AWS ELB Application Load Balancer and just stop the old container once the ELB finishes draining it.

**Comment by OnixGH** [comment]
Thanks for the response!
