### ISSUE TITLE
mesg: ttyname failed: Success

### ISSUE THREAD

**Issue by ain** [phusion/passenger-docker#145]
The login shell throws `mesg: ttyname failed: Success`. Would it be possible to get rid of this, any ideas?

**Tested images**:
- phusion/passenger-ruby21
- phusion/passenger-ruby23

**Platform**:

```
Docker for Mac 1.12.0-rc4-beta20 (build: 10404)
Mac OS X 10.11.6
```

**Comment by kelset** [comment]
I have the same issue - any news about it?

I found this other [issue](https://github.com/lxc/lxd/issues/1896) which seems to point in the right direction but I can't figure out how to fix it.

**Comment by OnixGH** [comment]
Unfortunately, I don't see what we can do about this. See also: https://github.com/lxc/lxd/issues/1724
