### ISSUE TITLE
Will security updates for ruby versions be released now we're using RVM

### ISSUE THREAD

**Issue by jebw** [phusion/passenger-docker#147]
This is more of a question but is potentially a security issue - "Will new releases happen to concide with new Ruby releases"

Previously the docker images for the various ruby versions have been released quite intermittently - there was 8 months between 0.9.18 and 0.9.19 - the recommended solution to this was to include `RUN apt-get update; apt-get upgrade` in  images derived from your base images.

Presumably now that ruby is instead supplied by RVM instead of Apt that will no longer work - what is the recommended approach to ensuring the current ruby bugfix release is used (ie 2.3.1, or 2.2.5)?

Thanks for great base images

**Comment by FooBarWidget** [comment]
If we do not release as quickly as you like, then the next easiest solution is to locally fork the image. The Ruby version to be installed is inferred from the filename in /image. For example you can rename ruby-2.3.1.sh to ruby-2.3.2.sh. Then you run 'make build_ruby23 NAME=yourorg/yourimagename' and there is your updated base image.

**Comment by jebw** [comment]
Ok, thanks for the info
