### ISSUE TITLE
Stop nginx with SIGQUIT instead of docker stop's SIGTERM signal

### ISSUE THREAD

**Issue by schuylr** [phusion/passenger-docker#149]
As suggested in the [issue I opened in phusion/baseimage-docker](https://github.com/phusion/baseimage-docker/issues/335#issuecomment-242425175), I decided to repost the issue here.

I'd like to see nginx stopped gracefully with the `SIGQUIT` signal when `docker stop` is invoked, so there's at least an attempt to drain connections rather than reset them. See my referenced issue for more information on references and the suggestion of a wrapper script around `nginx`.

I don't use this image specifically, but ideas on a best practice for the wrapper script would be very helpful, and probably beneficial to the contribution of this Docker image.

**Comment by schuylr** [comment]
Finally got around to this, here is my `run` script implementation of a signal handler for remapping to Nginx properly:

```bash
#!/bin/sh
# `/sbin/setuser memcache` runs the given command as the user `memcache`.
# If you omit that part, the command will be run as root.
# We're omitting that part.

set -x
pid=0

# SIGHUP handler
hup_handler() {
  if [ $pid -ne 0 ]; then
    echo "Sending SIGHUP to nginx pid $pid" >> /var/log/nginx.log
    kill -s HUP "$pid"
    echo "Successfully reloaded nginx process $pid" >> /var/log/nginx.log
  else
    echo "Nginx was not reloaded because pid was $pid"
  fi
}

# SIGKILL handler
kill_handler() {
  if [ $pid -ne 0 ]; then
    echo "Sending SIGKILL to nginx pid $pid" >> /var/log/nginx.log
    kill -s KILL "$pid"
    wait "$pid"
    echo "Successfully killed the Nginx process $pid"
  else
    echo "Exiting without SIGQUIT because pid was $pid" >> /var/log/nginx.log
  fi
  exit 137; # 128 + 9 == SIGKILL
}

# SIGTERM handler
term_handler() {
  if [ $pid -ne 0 ]; then
    echo "Sending SIGQUIT to nginx pid $pid" >> /var/log/nginx.log
    kill -s QUIT "$pid"
    wait "$pid"
    echo "Successfully exited the Nginx process $pid" >> /var/log/nginx.log
  else
    echo "Exiting without SIGQUIT because pid was $pid" >> /var/log/nginx.log
  fi
  exit 143; # 128 + 15 == SIGTERM
}

trap 'kill ${!}; hup_handler' SIGHUP
trap 'kill ${!}; term_handler' SIGTERM
trap 'kill ${!}; kill_handler' SIGKILL

# run application
/opt/nginx/sbin/nginx & # >> /var/log/nginx.log 2>&1 &
pid="$!"

echo "Kicking off wait, nginx pid is $pid" >> /var/log/nginx.log
# wait forever
while true
do
  tail -f /dev/null & wait ${!}
done
```

This allows `stop`, `kill` and `reload` to all work correctly, although it is possible for a hung nginx process to become detached from the script if you send a `SIGTERM` and `SIGKILL` in succession. I haven't found a graceful workaround but this is adequate enough for me in the meantime.

**Comment by af12066** [comment]
Did you try [`STOPSIGNAL`](https://docs.docker.com/engine/reference/builder/#stopsignal) on your Dockerfile?

**Comment by dzuelke** [comment]
Just FYI, your script is terminating itself incorrectly.

You must not `exit 128+$code`, that's just how the shell represents it.

Programs terminating in response to a signal must instead terminate themselves using the same signal, meaning you have to do `kill -TERM $$` instead.

This is so that a calling program can determine whether a program exited on its own accord, or in response to a signal (`WIFEXITED` vs `WIFSIGNALED`). This matters for instance for Ctrl+C handling in a loop, see https://mywiki.wooledge.org/SignalTrap#Special_Note_On_SIGINT_and_SIGQUIT

Remember you then also have to reset the traps first in your traps (`trap - SIGNAL`), otherwise you get an infinite loop.

P.S. What's the purpose of `kill $!` in each trap?

**Comment by groyoh** [comment]
My team solved this issue by creating a `sv` control file for the term command e.g. `/etc/service/nginx/control/t`:

```sh
#!/bin/bash
set -e

sv q nginx
```

With that, there's no need for an extra script as it would "translate" sigterm to sigquit for NGINX. For more info, check the [runsv documentation](http://smarden.org/runit/runsv.8.html).
