### ISSUE TITLE
Problems with RVM

### ISSUE THREAD

**Issue by maurosbu** [phusion/passenger-docker#150]
Hi folks,
I'm trying to dockerize an existing rails app and I get the following error:

```
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.3.1/bin' is not at first place,
                 usually this is caused by shell initialization files - check them for 'PATH=...' entries,
                 it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
                 to fix temporarily in this shell session run: 'rvm use ruby-2.3.1'.
```

I'm using the following image/version:

```
FROM phusion/passenger-ruby23:0.9.19
```

Many thanks in advance.

Mauro

**Comment by maurosbu** [comment]
A solution can be found here:
https://groups.google.com/forum/#!topic/passenger-docker/derT8VVDvbo

**Comment by amingilani** [comment]
For completeness' sake, i'll add it here.

> After following it the above I just needed to change my nginx conf file to:
> 
> `passenger_ruby /usr/local/rvm/gems/ruby-2.3.1@rails5_coolon_light_architect/wrappers/ruby;`
>  -- [Andrew Pietsch](https://groups.google.com/d/msg/passenger-docker/derT8VVDvbo/mkpVNSfOAQAJ)

**Comment by carukc** [comment]
yes, the wrappers seem to be the way to resolve the problem for nginx butI'm seeing the same problem when I try to use rvm from the command line, even from the 'app' user.

The warning says that I should use  'rvm get stable --auto-dotfiles' but when I run this I get 

----

GPG signature verification failed for '/usr/local/rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

----

Even after installing the keys I still get the message, no matter what user I'm on.  Does anyone know how to get rvm working on the command line for container users?

Thanks
Chris

**Comment by carukc** [comment]
I think that this is only a warning... rvm seems to be working ok.

**Comment by CamJN** [comment]
fixed in https://github.com/phusion/passenger-docker/commit/01238eb005915ae8bdc73ba2471171ced445baa3
