### ISSUE TITLE
Could not spawn process for application

### ISSUE THREAD

**Issue by sbu** [phusion/passenger-docker#151]
Hi folks,
Im trying to follow the tutorial at https://chengl.com/using-docker-for-rails-development/ but I get the following error:    

```
Could not spawn process for application /home/app/rails_on_docker_for_dev: An error occurred while starting up the preloader: it did not write a startup response in time.
```

I get the same error with an existing rails application.

Any idea? 
Many thanks in advance.

**Comment by OnixGH** [comment]
This issue is not related to the passenger-docker container. It's a message from Passenger saying that your application didn't start within the [default timeout](www.phusionpassenger.com/library/config/reference/?a=passenger_start_timeout).
