### ISSUE TITLE
Run time passenger configuration

### ISSUE THREAD

**Issue by dmitrym0** [phusion/passenger-docker#154]
Is there any guidance/best practices for configuring passenger itself during container runtime? In particular I'd like to tweak `PassengerMaxPoolSize` based on the host that the container is running on. In my googling, I found [envplate](https://github.com/kreuzwerker/envplate) which rewrites config files based on environment vars (which make this a little more 12 factor). Is this a good option? What else is out there?

**Comment by OnixGH** [comment]
What about just setting the [PASSENGER_MAX_POOL_SIZE](https://www.phusionpassenger.com/library/config/standalone/reference/#--max-pool-size-max_pool_size) env variable?

**Comment by dmitrym0** [comment]
I saw that, but I assumed that it applies to "passenger standalone" only, which is not the same as passenger invoked by nginx since it doesn't appear [here](https://www.phusionpassenger.com/library/config/nginx/reference/). Is that right?

**Comment by OnixGH** [comment]
Oh, yeah that's right, sorry. I saw "docker" and assumed Standalone.

Maybe you can use [Lua](https://docs.apitools.com/blog/2014/07/02/using-environment-variables-in-nginx-conf.html) then? I think that module is part of the default [apt build](https://github.com/phusion/passenger_apt_automation/blob/master/debian_specs/nginx/rules.erb#L123). Haven't tried anything like this before though.

**Comment by dmitrym0** [comment]
No worries, thanks for trying. Is passenger in passenger-docker standalone or not? I'm surprised nobody else has encountered this issue..

**Comment by dmitrym0** [comment]
Doh, looks like there's no clean way of doing this. You have to configure `passenger_max_pool_size` via the nginx's `http` directive which is only available in `/etc/nginx/nginx.conf` which is prebaked. Not sure how to do this cleanly without modifying the base image..

**Comment by FooBarWidget** [comment]
You can just overwrite nginx.conf with instructions inside your Dockerfile.

**Comment by dmitrym0** [comment]
@FooBarWidget I'd prefer not to do that for easier upgradability. In any case, it turns out that you can drop config files in `/etc/nginx/conf.d/`. I added a passenger.conf.template like so:


```
client_max_body_size 100M;
passenger_pre_start http://localhost;
# by default 2 passengers
passenger_max_pool_size ${PASSENGER_MAX_POOL_SIZE:-2};
```

which I process with [envplate](https://github.com/kreuzwerker/envplate) on container startup. Working ok.
