### ISSUE TITLE
failed to open configuration file '/root/.dpkg.cfg'

### ISSUE THREAD

**Issue by Startouf** [phusion/passenger-docker#160]
I am using the passenger-docker to build a refined base container and I am deploying my app inside it during Capistrano 
*I choose this way, because Capistrano handles cleverly Rails deployment (shared files, secrets, amazon, lot of Capistrano gems that add behavior). I am working with the underrated gem `capistrano-deploy_into_docker`*

However, during the container creation I run several times into the following error
> failed to open configuration file '/root/.dpkg.cfg'

Despite having several times this warning/error during docker build steps, the steps proceed as usual, but I'm still wondering what happens...
Here is my Dockerfile

```
# Dockerfile
FROM phusion/passenger-customizable:0.9.19
ENV HOME /root

CMD ["/sbin/my_init"]


RUN /pd_build/utilities.sh
RUN /pd_build/ruby-2.3.*.sh
RUN /pd_build/nodejs.sh

#################
## CUSTOM-CODE ##
#################

RUN apt-get install -y imagemagick

# Add nginx configuration and enable nginx
RUN rm /etc/nginx/sites-enabled/default
ADD docker/nginx.conf /etc/nginx/sites-enabled/webapp.conf
ADD docker/rails-env.conf /etc/nginx/main.d/rails-env.conf
RUN rm -f /etc/service/nginx/down
EXPOSE 80
EXPOSE 443

# Add ssl keys
RUN mkdir /ssx && chmod 711 /ssx
ADD docker/ssx/webapp.chained.crt /ssx/webapp.chained.crt;
ADD docker/ssx/webapp.key.nopass /ssx/webapp.key.nopass;
RUN chown app:app /ssx/webapp.*
RUN chmod 440 /ssx/webapp.*

# Prepare Rails app folder
RUN mkdir /home/app/webapp
# ADD . /home/app/webapp ==> Leave that for capistrano
RUN chown -R app:app /home/app/webapp

# SSH related files 
RUN rm -f /etc/service/sshd/down
ADD docker/ssx/id_rsa /root/.ssh/id_rsa
ADD docker/ssx/id_rsa.pub /root/.ssh/id_rsa.pub
RUN cp /root/.ssh/id_rsa.pub /home/app/.ssh/id_rsa.pub
RUN cp /root/.ssh/id_rsa /home/app/.ssh/id_rsa
ADD docker/ssx/authorized_keys /tmp/
RUN cat /tmp/authorized_keys >> /root/.ssh/authorized_keys
RUN cat /tmp/authorized_keys >> /home/app/.ssh/authorized_keys
RUN rm -f /tmp/id_rsa.pub
RUN chmod 400 /root/.ssh/id_rsa /home/app/.ssh/id_rsa
RUN chmod 444 /root/.ssh/id_rsa.pub /home/app/.ssh/id_rsa.pub
RUN chown app:app /home/app/.ssh/id_rsa /home/app/.ssh/id_rsa.pub

USER app

# install bundler dependencies to enable caching
WORKDIR /home/app/webapp
ADD Gemfile /home/app/webapp/
ADD Gemfile.lock /home/app/webapp/
RUN mkdir -p /home/app/webapp/shared/bundle
RUN bundle install --path /home/app/webapp/shared/bundle --without development test deploy rspec import

USER root

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

```

**Comment by vlymar** [comment]
I had the same issue happen when i run `USER app` before the bundle install. Error went away when I installed bundle as root.

I'm also curious if there is a correct workflow for bundling as the `app` user, probably involves changing some permissions.

**Comment by adamaig** [comment]
This particular error seems to be related to the HOME variable setting. I'd like to know why the example shows setting HOME to /root, and if that is actually needed.

**Comment by OnixGH** [comment]
@Startouf as @adamaig noticed, you set `ENV HOME /root` but then `USER app`, so you end up with processes of user app trying to write to the homedir of root, which is not allowed.
