### ISSUE TITLE
Add the nodesource repo for Node.js 7.x

### ISSUE THREAD

**Issue by hamid-elaosta** [phusion/passenger-docker#179]
The node image documentation says it uses the Chris Lea PPA (https://launchpad.net/~chris-lea/+archive/ubuntu/node.js/) which doesn't appear to be true, as I can apt upgrade it to 4.x, however, it should move to the current repo (See: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

**Comment by CamJN** [comment]
fixed in https://github.com/phusion/passenger-docker/commit/e9e6f96839e171cf1d7a0fd63639b871b27a6a73
