### ISSUE TITLE
Issues with logging in passenger-ruby21:0.9.20

### ISSUE THREAD

**Issue by robscott** [phusion/passenger-docker#182]
We're attempting to upgrade from `passenger-ruby21:0.9.19` to `passenger-ruby21:0.9.20` to get to Passenger 5.1. Unfortunately this change seems to break logging to stdout for us. Our Rails app simply logs to stdout, and it would be nice if that could actually reach the stdout for the container (as it did in 0.9.19). Here's what I'm seeing for the container logs:
![screen shot 2017-03-30 at 10 00 14 pm](https://cloud.githubusercontent.com/assets/419322/24533331/fcc0134c-1594-11e7-847c-b105e6a0e121.png)

That's the full extent of what's being sent to Docker as far as I can tell. On the other hand, the nginx error log has our full application logs in `/var/log/nginx/error.log`:
![screen shot 2017-03-30 at 10 00 01 pm](https://cloud.githubusercontent.com/assets/419322/24533319/f2302520-1594-11e7-9c62-b169b469a710.png)

Also noteworthy, the nginx-log-forwarder does still appear to be running on the container. 
![screen shot 2017-03-30 at 10 03 09 pm](https://cloud.githubusercontent.com/assets/419322/24533373/46c14c54-1595-11e7-9242-e145e6f4c227.png)

Is there anything obvious I'm missing here? Thanks in advance for any help!

**Comment by bsedat** [comment]
I noticed that manually restarting the nginx-log-forwarder in the container seemed to bring the logs back. I'm not sure what the underlying issue is yet though.

**Comment by CamJN** [comment]
should be fixed in https://github.com/phusion/passenger-docker/commit/ffcc0ec20cb83fb8238e7e928bb496df7c5cc65a
