### ISSUE TITLE
Log forwarding not working in passenger-ruby23

### ISSUE THREAD

**Issue by Wedontplay** [phusion/passenger-docker#183]
Hi, I'm using ```phusion/passenger-ruby23``` and nginx logs aren't forwarded to ```STDOUT```.
I checked and the ```nginx-log-forwarder``` is running, here is the output of a ```ps aux | grep nginx-log-forwarder``` launched inside the container:

```
root        11  0.0  0.0   4236    72 ?        Ss   Apr14   0:00 runsv nginx-log-forwarder
root     19103  0.0  0.0  14508   988 ?        S+   09:01   0:00 grep --color=auto nginx-log-forwarder
``` 
also launching a ```tail -F /var/log/nginx/error.log``` tail can't follow the log, it print it but it doesn't update it anymore. Any Idea of what the issue could be? 

maybe is linked to #182 ?

I also tried to restart ```nginx-log-forwarder``` but nothing change

**Comment by CamJN** [comment]
should be fixed in https://github.com/phusion/passenger-docker/commit/ffcc0ec20cb83fb8238e7e928bb496df7c5cc65a
