### ISSUE TITLE
node version 4.2.6 in ruby24 image instead of v7.10.0

### ISSUE THREAD

**Issue by leifcr** [phusion/passenger-docker#185]
Node version is 4.2.6 in current ruby24 (0.9.21) docker image. 

Expected to be v7.10.0 from the changelog (https://github.com/phusion/passenger-docker/blob/master/Changelog.md#0921-release-date-2017-05-18)

**Comment by OnixGH** [comment]
The Ruby image is focused on Ruby support. The fact that Node is in it at all is a just a side effect of the image being based on the Ubuntu 16.04 image (which has Node 4.2.6). You can use the Node image or the Full image to get 7.10.

**Comment by leifcr** [comment]
@OnixGH Thanks. For webpacker support (rails5 js assets), node > 4.3 is required. Added note about version in #186

**Comment by OnixGH** [comment]
Thanks, I see your point.

**Comment by anlek** [comment]
I'm hitting the same issue, I'm trying to run Rails 5 with webpacker and it requires > 4.3.

**Comment by mech** [comment]
Using

`FROM phusion/passenger-ruby25`

Without doing anymore thing, Node is at 4.2.6

I think because of Webpacker, we need The Ruby image to also include recent version of Node:

`Webpacker requires Node.js >= 6.0.0 and you are using 4.2.6`
