### ISSUE TITLE
bash: rails: command not found on versions 0.9.21, 0.9.22 of passenger-ruby23, PATH problem?

### ISSUE THREAD

**Issue by maurosbu** [phusion/passenger-docker#191]
Hi, in order to be able to create new rails apps in my multi app development environment I added instructions to install last version of rails in Dockerfile

.env

    ...

    INSTALL_RAILS=true

    ...

Dockerfile

    ...

    ARG INSTALL_RAILS=false
    ENV INSTALL_RAILS ${INSTALL_RAILS}

    RUN if [ ${INSTALL_RAILS} = true ]; then \
        gem install rails \
    ;fi

    ...

Rails installs fine but executable cannot be found when using versions 0.9.21, 0.9.22 of passenger-ruby23.

**FROM phusion/passenger-ruby23:0.9.22**

    $ rails -v
    bash: rails: command not found
    $ echo $PATH
    /usr/local/rvm/gems/ruby-2.3.3/bin:/usr/local/rvm/gems/ruby-2.3.3@global/bin:/usr/local/rvm/rubies/ruby-2.3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin

**FROM phusion/passenger-ruby23:0.9.20**

    $ rails -v
    Rails 5.1.1
    $ echo $PATH
    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    
Is this a PATH problem?
Many thanks in advance.

**Comment by OnixGH** [comment]
Thanks for the report. Since we didn't officially tag 0.9.20, which commit did you use to build that?

**Comment by maurosbu** [comment]
In Dockerfile I set
   
    FROM phusion/passenger-ruby23:0.9.20

Is there a way to see the commit?

**Comment by maurosbu** [comment]
Tag tag 0.9.20 is present at the following link:
https://hub.docker.com/r/phusion/passenger-ruby23/tags/

**Comment by OnixGH** [comment]
OK, we can reproduce. Meanwhile, as a workaround, using `-l` works for me:
```
docker run -it --rm phusion/passenger-ruby23:0.9.22 /sbin/my_init -- /bin/bash -l
..
*** Running /bin/bash -l...
root@7a4394e14556:/# gem install rails
Fetching: i18n-0.8.4.gem (100%)
Successfully installed i18n-0.8.4
..
Fetching: rails-5.1.1.gem (100%)
Successfully installed rails-5.1.1
34 gems installed
root@7a4394e14556:/# rails -v
Rails 5.1.1
```

**Comment by CamJN** [comment]
I can actually reproduce on 0.9.20 as well, could you provide a minimal Dockerfile that exhibits the behaviour only on 0.9.21+ and not on 0.9.20?

**Comment by maurosbu** [comment]
@CamJN here it is!

Dockerfile

    FROM phusion/passenger-ruby23:0.9.20
    MAINTAINER Mauro Nidola <mauro.nidola@usi.ch>

    # Set correct environment variables.
    # ENV HOME /root

    # Use baseimage-docker's init process.
    CMD ["/sbin/my_init"]

    # update/upgrade system and install missing libraries
    RUN apt-get update && \
        apt-get upgrade -y -o Dpkg::Options::="--force-confold"

    # update rubygems & bundler
    RUN gem update --system && gem update bundler

    # install rails
    RUN gem install rails

    # Clean up APT when done.
    RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

docker-compose.yml

    version: '3'
    services:
      web:
        build:
          context: .


In order to use last version of image please change the first line of Dockerfile to

    FROM phusion/passenger-ruby23:0.9.22

Useful commands:

    # build
    docker-compose build --no-cache

    # bring containers up
    docker-compose up -d

    # exec bash
    docker-compose exec web bash


Hope this helps!

Mauro

**Comment by OnixGH** [comment]
@maurosbu using your docker compose commands, the workaround `docker-compose exec web bash -l` works with 0.9.22.

**Comment by maurosbu** [comment]
@OnixGH Yes, it works.

**Comment by OnixGH** [comment]
I traced the change in behavior to https://github.com/phusion/passenger-docker/commit/8eba3011b0f8a4e309f0510ddf5610614c3131a0, where we switched the parent image [baseimage-docker](https://github.com/phusion/baseimage-docker) from v0.9.19 to 0.9.21.

So the root cause appears to be higher up.

**Comment by CamJN** [comment]
It has been determined that the current behaviour is the correct behaviour and the previous behaviour was incorrect. Bash should not be a login shell unless the `-l` flag is passed. Luckily it is simple enough to get the behaviour you want.
