### ISSUE TITLE
hub.docker.com - phusion/passenger-*:latest not updated to latest releases

### ISSUE THREAD

**Issue by bwalding** [phusion/passenger-docker#197]
`0.9.25` was released late August, however the `latest` is still pointing at `0.9.22` (for passenger-ruby24)

Given that there are security fixes (updated Nginx / Passenger) in 0.9.25 - is there any reason that `latest` wasn't updated?

**Comment by OnixGH** [comment]
Thanks! Our [release Makefile](https://github.com/phusion/passenger-docker/commit/747fb361df20f214c6eacc75d9fe4bf114639543) was missing the push for the latest tag.
