### ISSUE TITLE
rvm is broken in 0.9.26?

### ISSUE THREAD

**Issue by maxivak** [phusion/passenger-docker#202]
I am using image phusion/passenger-full:0.9.26.

```
docker run -d --name my-apps phusion/passenger-full:0.9.26 /sbin/my_init 

docker exec -ti my-apps bash

root@c0f19a9c84f7:/# rvm list
bash: rvm: command not found

which rvm

```

but RVM works in 0.9.20.

What happened with RVM in new version passenger-full:0.9.26 ?

**Comment by maxivak** [comment]
when I run `docker exec -ti my-apps bash` it runs bash in non-login shell.
after I run `bash -l` it sources all environment for rvm and it works.

```
bash -l

echo $PATH

/usr/local/rvm/gems/ruby-2.4.2/bin:/usr/local/rvm/gems/ruby-2.4.2@global/bin:/usr/local/rvm/rubies/ruby-2.4.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin

root@528ad7518472:/# rvm list

rvm rubies

   jruby-9.1.2.0 [ x86_64 ]
   ruby-2.0.0-p648 [ x86_64 ]
   ruby-2.1.9 [ x86_64 ]
   ruby-2.2.8 [ x86_64 ]
   ruby-2.3.5 [ x86_64 ]
=* ruby-2.4.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

root@528ad7518472:/# echo $PATH
/usr/local/rvm/gems/ruby-2.4.2/bin:/usr/local/rvm/gems/ruby-2.4.2@global/bin:/usr/local/rvm/rubies/ruby-2.4.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin
root@528ad7518472:/# rvm list

rvm rubies

   jruby-9.1.2.0 [ x86_64 ]
   ruby-2.0.0-p648 [ x86_64 ]
   ruby-2.1.9 [ x86_64 ]
   ruby-2.2.8 [ x86_64 ]
   ruby-2.3.5 [ x86_64 ]
=* ruby-2.4.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

```
it worked differently in version 0.9.20 .

**Comment by CamJN** [comment]
The change was probably one of these two: https://github.com/phusion/passenger-docker/commit/01238eb005915ae8bdc73ba2471171ced445baa3 and https://github.com/phusion/passenger-docker/commit/6590a0a57fd227a9f44dd2adfc65251dd7cc1eab.

That said [this is just how rvm works](https://rvm.io/support/faq#what-shell-login-means-bash-l), it requires a login shell to source it's environment. So I'm not convinced this is a bug.

**Comment by CamJN** [comment]
Closing b/c this is expected behaviour for rvm.
