### ISSUE TITLE
Node.js LTS

### ISSUE THREAD

**Issue by majgis** [phusion/passenger-docker#203]
Node.js 8.9.1 LTS is available, any plans to update?

Also, if we only want to track LTS versions, is there any solution for that?

**Comment by SandHilt** [comment]
Why don't use NVM and install with flag ``--lts``?

**Comment by majgis** [comment]
I can do that.  It might be a good sign that node.js should be excluded altogether and we bring our own.  The first impression it makes is that the container is no longer maintained.

**Comment by OnixGH** [comment]
@majgis the container is still maintained, I just didn't think Node 7 is that old. Looking at the history I do see we accepted a PR that switched to a non-LTS version, I think we should avoid that in the future. I've added it to the upgrade checklist (mostly synced to Passenger releases).

**Comment by OnixGH** [comment]
Upgraded to 8.9.4 LTS via https://github.com/phusion/passenger-docker/commit/88691051d98db79c0df67cb13f6a579e8200995b.
