### ISSUE TITLE
Modify example Dockerfile and readme.md to include new COPY/ADD --chown command

### ISSUE THREAD

**Issue by skunkworker** [phusion/passenger-docker#205]
With the release of [v17.09.0-ce](https://github.com/docker/docker-ce/releases/tag/v17.09.0-ce) docker now supports the --chown argument with `COPY` and `ADD`.

Instead of running 
`RUN chown -R app:app /home/app/webapp` 
and taking a long time you can now use
`COPY --chown=app:app . /home/app/webapp`
to copy the files over with the correct permissions.

Since I haven't seen this documented anywhere I am creating this issue and also a PR to modify the commands in the readme.md file.

**Comment by OnixGH** [comment]
Merged via https://github.com/phusion/passenger-docker/commit/8a4a4c90a229b9984099a8e1cd166503a37f072d.
