### ISSUE TITLE
Image phusion/passenger-ruby23 installing wrong ruby version?

### ISSUE THREAD

**Issue by jpmermoz** [phusion/passenger-docker#209]
Hi there, I'm using this image in my dockerfile: phusion/passenger-ruby23
According to the documentation and source code, this image should install ruby 2.3.5, but instead I can see it's installing ruby 2.3.3.

This is the output from my container:

`root@a47c6b52cdce:~# ruby -v`
`ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]`

Is anyone else getting this issue?
Thank you.

**Comment by CamJN** [comment]
Have you made sure that you've pulled the latest image?

**Comment by Salman888** [comment]
The same problem occurred in Phusion/passenger-ruby21 too. 
Actually, I ssh into the container and found that there was no /pd_build/ exist.
There was an error appeared that ""/pd_build/ruby-2.1.*.sh"not found" so I had moved the image folder from GitHub as /pd_build/ folder while building the image then after running the container and exec into it, I found ruby2.0.0 was installed and I think this is the reason my application is not working.
Please help me out
Early reply is highly appreciated

**Comment by OnixGH** [comment]
This is probably due to the fact that up till 0.9.28 we didn't update the `latest` tag of our images (https://github.com/phusion/passenger-docker/issues/197), which means latest was pointing to 0.9.22 images. This will be fixed with 0.9.29, feel free to reopen if it's still an issue after that.
