### ISSUE TITLE
cannot load such file -- bundler/dep_proxy (LoadError)

### ISSUE THREAD

**Issue by hipertracker** [phusion/passenger-docker#215]
I created a simple Rails project (with `rails new tescior`), added a `Dockerfile` and `docker-compose.yml`, nothing special. The image is built, composed, server stars but it fails with strange  error `cannot load such file -- bundler/dep_proxy (LoadError)` I create a repo for reproducing the bug https://github.com/hipertracker/rails-passenger-docker-test

**Comment by hipertracker** [comment]
The problem [has been fixed](https://github.com/hipertracker/rails-passenger-docker-test/commit/959f9b05a6578adca057bbe961fa7a8876ccf7a3) by:
* deleting Gemfile.lock
* adding `gem txinfo-data` to Gemfile
* adding `RUN gem update --system` to Dockerfile

**Comment by maurosbu** [comment]
@hipertracker In order to solve the problem I had to reinstall bundler.
    
    gem install bundler

**Comment by L0rD59** [comment]
Hi all,

Same problem here : `gem install bundler` works fine, but what did you do that ?

Any chance to solve this point ?

Thx

**Comment by j-mcnally** [comment]
for me, i hand to remove bundle exec from my rake command. i think its rvm related.

**Comment by blarvin** [comment]
@maurosbu reinstalling bundler worked for me. Thanks! I'm a real greenhorn, so... not too sure whats wrong. But I tell you it is odd that this error came up. THE VERY LAST THING I DID IN THIS REPO WAS FINALLY GET THE SERVER TO FIRE UP.  Then I committed, pushed, shut down machine, went to bed. Next day, VERY FIRST THING I DID: run ````bin/rails server```` ... and got this error. I did nothing else!

**Comment by thierryfornetti** [comment]
@Wedontplay did some research about this, I've explained what he found int [this post](https://github.com/phusion/passenger-docker/issues/220#issuecomment-408058984)
