### ISSUE TITLE
websockets support?

### ISSUE THREAD

**Issue by johnjelinek** [phusion/passenger-docker#22]
How do I upgrade nginx to use websockets with passenger apps if I'm not proxying to a standalone passenger instance?

**Comment by OnixGH** [comment]
Please open a ticket on the Passenger issue or post to the [forum](https://groups.google.com/forum/#!forum/phusion-passenger) for issues related to Passenger itself. We're not aware of issues with Faye in Passenger 5.1.x at this time.
