### ISSUE TITLE
RVM issue 

### ISSUE THREAD

**Issue by programingnotes** [phusion/passenger-docker#220]
- Expectation
   - Given  a sinatra project with ruby version 2.5.1 (in `.ruby-version` file and also in `Gemfile`)  and a Dockerfile that looks like this: 
    ```
      FROM phusion/passenger-ruby25
      LABEL maintainer="myprogramingnotes@gmail.com"

      # Set correct environment variables.
      ENV HOME /root

      # Use baseimage-docker's init process.
      CMD ["/sbin/my_init"]

      # Enable nginx and Passenger 
      RUN rm -f /etc/service/nginx/down

      # Remove the default site
      RUN rm /etc/nginx/sites-enabled/default

      # Create virtual host 
      ADD app-virtual-host/vhost.conf /etc/nginx/sites-enabled/vhost.conf

      # Prepare folders
      RUN mkdir /home/app/webapp

      # run bundle in a cache efficient way 
      WORKDIR /tmp 
      COPY sinatra/Gemfile /tmp/
      COPY sinatra/Gemfile.lock /tmp/
      RUN bundle install 

      # place sinatra app in /home/app/webapp with the correct ownership.
      # ownership changes to the user (called app) created by Passenger Image
      COPY --chown=app:app sinatra/  /home/app/webapp

      # Clean up APT when done.
      RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    ```  
  I expect that the web app should be available (up and running)

- Errors

  

1. RVM Ruby Version Error: 

  ```
    cannot load such file -- bundler/dep_proxy (LoadError) 
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `block in expand_dependencies'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `each'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `expand_dependencies'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:806:in `converge_locked_specs'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:247:in `resolve'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:363:in `activate_gem'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:527:in `running_bundler'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:91:in `preload_app'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
  ```

  **Note:** inside the container, the command`ruby -v` returns `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`

  It appears that there is a discrepancy between the app and the image `/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/`.  

  

2. Bundler Version Error: 
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.16.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

I think I am missing a step that has to do with the version of passenger-docker I am running - is the expectation that users of the image will customize this further?  
  - if yes, then how is this different from `husion/passenger-customizable`? the docs are a bit confusing

**Comment by programingnotes** [comment]
Although I have resolved my issue, I still have questions but will document the steps taken to resolve the issue in case it helps someone else or someone can provide insights/a better way to solve this. 

1. Here are the steps I took:
    - I ended up installing the ruby version that I wanted  and also installing bundler 
    ```
      FROM phusion/passenger-ruby25
      LABEL maintainer="email-address"

      # Set correct environment variables.
      ENV HOME /root

     # Use baseimage-docker's init process.
     CMD ["/sbin/my_init"]


      #explicitly opt-in for features
      RUN /bin/bash -l -c "rvm install 2.5.1"
      RUN gem install bundler --no-ri --no-rdoc 
    ``` 



1. Questions
    - If an image variant already comes packaged with a specific ruby version, like `phusion/passenger-ruby25 - Ruby 2.5.` is expected to come packaged with `ruby 2.5.1`, then why did I need to install said version again ` RUN /bin/bash -l -c "rvm install 2.5.1"`

  - the same question applies to having to install bundler

**Comment by thierryfornetti** [comment]
@Wedontplay did a research about this problem, I write what we found.

The original problem was an error when launching a container
```
LoadError: cannot load such file -- bundler/dep_proxy
```

The real problem is that it can't use the command `rails` or `bin/rails` or `rake` because **it doesn't find the rails path**.
We can see that based on the command we use to launch the container we have different results for $PATH.

With `docker-compose run --rm api bash -c "echo $PATH"`
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

With `docker-compose run --rm api bash -l`, then we launch `echo $PATH` inside the container
```
/usr/local/rvm/gems/ruby-2.5.1/bin:/usr/local/rvm/gems/ruby-2.5.1@global/bin:/usr/local/rvm/rubies/ruby-2.5.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin
```

The main point is `/usr/local/rvm/gems/ruby-2.5.1/bin`, if we add it to $PATH when launching the container we can use the command `rails` (but we can't use `bin/rails`).
We use the container to launch a Rails server, the **complete command to launch the container** becomes:
```
command: bash -c "export PATH="/usr/local/rvm/gems/ruby-2.5.1/bin:$PATH" && rm -f tmp/pids/server.pid && rails s -p 3001 -b '0.0.0.0' -e development"
```

This is a problem of the phusion passenger image, because ruby, rails, rvm, bundle and their dependencies should be already installed and available inside the container.
We found the same problem in both passenger-ruby24 and passenger-ruby25.

The first time we run across this problem was 9 march 2018, so it has to be something happened between the end of 2017 and the first months of 2018.

Above that, when launching our project in a staging environment, [nginx](https://www.nginx.com/) can't find none of the files inside bundle.
In the end we solved it with `RUN gem install bundler --no-ri --no-rdoc`.

**Comment by CamJN** [comment]
since there seems to have been a resolution i'll close this, however for issues like this, it's usually the case that you need to be using the `app` user, and starting your app via the runit->nginx->passenger->app chain which sets up the environment for rvm for you.
