### ISSUE TITLE
Update to Ubuntu 18.04, aka baseimage 11

### ISSUE THREAD

**Issue by edward-ellis** [phusion/passenger-docker#227]
I am currently installing a current version of [FreeTDS ](http://www.freetds.org/) from a tarball because the package for Ubuntu 16.04 is so far behind.  If passenger-docker were to update to Ubuntu 18.04, I could go back to using just supported packages.  The baseimage just release version 11 which is based on 18.04.
If you like I would be happy to begin a baseimage 11 branch and submit a PR.
How does this fit with your plans for making a version based on version 11 available?

**Comment by P9GIT** [comment]
Agree, please update to Ubuntu 18.04 LTS.

**Comment by JIucToyxuu** [comment]
Absolutely, I ask the same.

**Comment by CamJN** [comment]
Done
