### ISSUE TITLE
Dockerising Rails application: Error - “unexpected ”d“ in /etc/nginx/conf.d/00_app_env.conf:1” while running “docker-compose up”

### ISSUE THREAD

**Issue by vikramjadon921995** [phusion/passenger-docker#229]
I am dockerising my rails application with nginx
, passenger
, ruby 2.4.0
and rails 5.1.6
.

I was following this to setup phusion/passenger on docker.

When I run docker-compose up
. It is throwing following error:

nginx: [emerg] unexpected "d" in /etc/nginx/conf.d/00_app_env.conf:1
Here is the stackoverflow question that I posted: https://stackoverflow.com/questions/52112629/dockerising-rails-application-error-unexpected-d-in-etc-nginx-conf-d-00-a

**Comment by CamJN** [comment]
Closing as stale.
