### ISSUE TITLE
Wrong default Ruby version in passenger-full 1.0.1

### ISSUE THREAD

**Issue by rodrigobdz** [phusion/passenger-docker#236]
I expect **phusion/passenger-full:1.0.1** to have `Ruby 2.5.3` as default but it actually has `jruby 9.2.0.0` set as default.

I've created a [MCVE](https://stackoverflow.com/help/mcve) to reproduce the bug:
https://github.com/rodrigobdz/passenger-full-ruby-bug

**Comment by tim-millar** [comment]
Same issue here. Also, `rvm` doesn't seem to be available, I get an error when I try to use it to install a different version of ruby.

**Comment by tf** [comment]
Might be related to #299.

**Comment by CamJN** [comment]
This should be fixed now
