### ISSUE TITLE
redis.conf bind error

### ISSUE THREAD

**Issue by alucardpj** [phusion/passenger-docker#237]
I use passenger-customizable:1.0.1 to build my docker image. And I enabled the redis. but when I run the image it keep reporting error in /var/log/redis-server.log

> Creating Server TCP listening socket ::1:6379: bind: Cannot assign requested address

I checked the redis.conf file, and the default config is:

> bind 127.0.0.1 ::1

if I change it to

>  bind 127.0.0.1

everything restores normal.
so is it a configuration error?

**Comment by ztrange** [comment]
I have the exact same problem. Resolved it as you said:

```
# Enable the redis service.
RUN rm -f /etc/service/redis/down
# Fix redis config: bind -- config for passenger-full:1.0.1
RUN sed -i 's/^bind 127.0.0.1 ::1/bind 127.0.0.1/' /etc/redis/redis.conf
```

**Comment by CamJN** [comment]
Limiting your image to ipv4 when that's all that's available is fine, but not something that should be baked in.
