### ISSUE TITLE
Can't get Rails to find env variables both in conf.d and main.d

### ISSUE THREAD

**Issue by mayordwells** [phusion/passenger-docker#248]
I have followed the instructions in the readme file and I have done as required.

In case we need some environmental variables in Nginx
```
ADD rails-env.conf /etc/nginx/main.d/rails-env.conf
ADD rails-env.conf /etc/nginx/conf.d/rails-env.conf
```
The whole app is not working in ECS container because of this. 
Here's me trying to access it from the ec2 instance. 
<img width="1280" alt="screen shot 2019-02-22 at 3 16 18 pm" src="https://user-images.githubusercontent.com/1370340/53242138-f097bc80-36b4-11e9-8a14-f70958d6c7f1.png">

Here's what my rails-env.conf looks like

```
env AWS_ACCESS_KEY_ID=AKccccccxxxx;

env AWS_SECRET_ACCESS_KEY=CE5Rlxcccccc;

env S3_BUCKET_NAME=weccc;

env RAILS_LOG_TO_STDOUT=enabled;

env SECRET_KEY_BASE=cfbf6ce63e00280f8fc3a4xxx;

env RAILS_MASTER_KEY=c64e019fxxxx;
```

How can I make the env variables be accessible to Rails?

**Comment by CamJN** [comment]
You want [passenger_env_var](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_env_var).

**Comment by mayordwells** [comment]
Thanks, @CamJN for your answer but this didn't work in an ECS environment.

However, in the task definition template and documentation, there's an environment key that takes an array of objects with key: value pairs, that's what I ended up using. 
Ref - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment

If you want to keep your credentials a super secret, you could also use AWS' SSM and then supply the values in the secrets array, also there in the documentation. 

Also, I later realized that conf.d does not allow the env directive in its folder so I had to remove this line from my Dockfile `ADD rails-env.conf /etc/nginx/conf.d/rails-env.conf`
