### ISSUE TITLE
Bundler now installed by default

### ISSUE THREAD

**Issue by jwhitcraft** [phusion/passenger-docker#260]
When using the customizable version of this container, we're running into this error:

```sh
/usr/local/rvm/bin/rvm-exec ruby-2.6.2@global gem install rake bundler rack --no-document
Using /usr/local/rvm/gems/ruby-2.6.2 with gemset global
ERROR: Error installing bundler: "bundle" from bundler conflicts with /usr/local/rvm/rubies/ruby-2.6.2/bin/bundle
Successfully installed rake-12.3.2 Successfully installed rack-2.0.7 2 gems installed
```

It would seem that bundler is now installed by default with the latest version of RVM, this was added here: https://github.com/rvm/rvm/pull/4413

The quick fix is just to remove the bundler from the default installed gems located here: https://github.com/phusion/passenger-docker/blob/master/image/buildconfig#L4

**Comment by mech** [comment]
Also encounter this issues. Ruby 2.6.2 somehow will not proceed further with ""bundle" from bundler conflicts with /usr/local/rvm/rubies/ruby-2.6.2/bin/bundle" error message.
