### ISSUE TITLE
How could I set timezone for container?

### ISSUE THREAD

**Issue by dieuit07** [phusion/passenger-docker#262]
Hi, my ec2 has timezone UTC+7, so that it inherits from the parent when initializing.
I would like to set it back to UTC. Trying do with `sudo timedatectl set-timezone UTC`. The system alert undefined command **timedatectl**, but there is no way for me to install that service inside container.

Could you please instruct me how to set timezone? Thanks

**Comment by mech** [comment]
I typically set the env during docker run, not sure if correct?

```
docker run -e TZ=Asia/Singapore ...
```

**Comment by CamJN** [comment]
This is more of a general docker question, so i'm closing it here.
