### ISSUE TITLE
Hold off on Ruby 2.6.4 bump.

### ISSUE THREAD

**Issue by skunkworker** [phusion/passenger-docker#267]
@CamJN I would be putting in a PR for bumping to Ruby 2.6.4. But I believe that should be prohibited following the discovery of a non-deterministic string corruption bug, and should be skipped for the likely upcoming 2.6.5 or patch.

https://bugs.ruby-lang.org/issues/16136

**Comment by CamJN** [comment]
2.6.5 is out, so that'll be the one that gets included

**Comment by skunkworker** [comment]
I mistakenly didn't update this issue once 2.6.4 got patched, though that could have caused some confusion.
