### ISSUE TITLE
Bump passenger-ruby25 to Ruby 2.5.6?

### ISSUE THREAD

**Issue by LocoDelAssembly** [phusion/passenger-docker#269]
Ruby 2.5.6 was released Aug 28th and comes with 40 bug fixes and a security fix: https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-5-6-released/

Could passenger-ruby25 be upgraded to 2.5.6?

Thanks

**Comment by CamJN** [comment]
I believe this is blocked by rvm 1.29.10: https://github.com/rvm/rvm/pull/4771

**Comment by LocoDelAssembly** [comment]
@CamJN sorry I don't understand... Why is that (merged?) pull request a blocker?
