### ISSUE TITLE
Docker image needs update and tag change

### ISSUE THREAD

**Issue by LocoDelAssembly** [phusion/passenger-docker#273]
A recently merged pull request (https://github.com/phusion/passenger-docker/pull/271) bring several ruby version changes. At Docker Hub these changes are not yet pushed and master branch currently still has 1.0.8 version:
https://github.com/phusion/passenger-docker/blob/63881a61db11f2d66db2962dddf3656bdcc1f7af/Makefile#L2

Should it be set to 1.0.9 and new images to Docker Hub be pushed?

**Comment by CamJN** [comment]
Yes, this should be done. That said there's nothing stopping people from cloning the repo and running `make build_all` themselves, so it's not that pressing.

**Comment by CamJN** [comment]
done
