### ISSUE TITLE
* Starting nginx nginx

### ISSUE THREAD

**Issue by hopewise** [phusion/passenger-docker#274]
I tried to start nginx using:

    service nginx start

but it stuck as:

    * Starting nginx nginx

Any idea? how to debug?

**Comment by nicksort** [comment]
I'm no expert but I'm going to recommend closing this issue unless he's been stuck for 23 days?  😃

**Comment by tomaszgieres** [comment]
@hopewise I got the same "issue".
Seems that it's not stuck, it's running. You can check that with opening a second terminal.

# first
```bash
root@5d73a5da7287:/home/app/webapp# service --status-all
 [ - ]  avahi-daemon
 [ - ]  cron
 [ - ]  dbus
 [ ? ]  hwclock.sh
 [ - ]  nginx
 [ - ]  procps
 [ - ]  ssh
 [ - ]  syslog-ng
 [ + ]  udev
 [ - ]  x11-common
root@5d73a5da7287:/home/app/webapp# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
root@5d73a5da7287:/home/app/webapp# service nginx start
 * Starting nginx nginx
```

# second
```bash
docker exec -it int_webapp_1 bash
root@5d73a5da7287:/home/app/webapp# service nginx status
 * nginx is running
```

Here nginx doesn't start as a daemon (see `/etc/nginx/nginx.conf:4`), this seems to be made on purpose however I'm not familiar with this project's philosophy and still have a limited perspective on docker.

**Comment by joshmello** [comment]
Try using the root user to manage (start|stop|restart) the nginx service should solve to the issue.

**Comment by hopewise** [comment]
Thank you @tomaszgieres

**Comment by JLoDoesIt** [comment]
I have the same issue even when running with root. If I figure it out, I'll post here.
The strange thing is that for me, nginx should start by default in this image, why should we start it manually or even with a dedicated entry point?
Let's see !

**Comment by JLoDoesIt** [comment]
Ok I found the issue, it was this line form the documentation:
RUN rm -f /etc/service/nginx/down
