### ISSUE TITLE
Bug for passenger-ruby25, it stopped to work on instalation for libmysqlclient-dev and npm

### ISSUE THREAD

**Issue by Marinofull** [phusion/passenger-docker#275]
I have an automated build from phusion/passenger-ruby25 which uses, among other packages, the following packages:

`apt-get install -y libmysqlclient-dev npm`

today, 27 January, it stopped to work and the problem seems to be regarding these two packages. When I run them individually I got these issues:

- for libmysqlclient-dev it installs its dependency `libssl-dev` and REMOVE: `libssl1.0-dev node-gyp nodejs-dev npm`

`apt-get install -y libmysqlclient-dev`
```
The following additional packages will be installed:
  libssl-dev
Suggested packages:
  libssl-doc
The following packages will be REMOVED:
  libssl1.0-dev node-gyp nodejs-dev npm
The following NEW packages will be installed:
  libmysqlclient-dev libssl-dev
```
- for npm it installs its dependencies: `libssl1.0-dev node-gyp nodejs-dev` and REMOVE: `libmysqlclient-dev libssl-dev`

`apt-get install -y npm`
```
The following additional packages will be installed:
  libssl1.0-dev node-gyp nodejs-dev
Suggested packages:
  debhelper
The following packages will be REMOVED:
  libmysqlclient-dev libssl-dev
The following NEW packages will be installed:
  libssl1.0-dev node-gyp nodejs-dev npm
```

And when i run the in a single line it brokes sometimes in `node-gyp` and others in the `libssl-dev`:
```
root@88d21c94cb80:/# apt-get install  -y libmysqlclient-dev npm
Reading package lists... Done
Building dependency tree
Reading state information... Done
libmysqlclient-dev is already the newest version (5.7.29-0ubuntu0.18.04.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed

```
output for `libssl-dev` error
```
 libmysqlclient-dev : Depends: libssl-dev (>= 1.1.1-1ubuntu2.1~18.04.5~) but it is not going to be installed
```

my version was previously phusion/passenger-ruby25:1.0.5, and I tried greater versions, even the latest tag without result.

**Comment by mahone3297** [comment]
I found the same error.
And I think it's not the phusion or docker's problem, it's the ubuntu's problem. So @Marinofull  change "phusion/passenger-ruby" version will not work.
The workaround maybe install one(npm) first and install another(libmysqlclient-dev) later. Npm we use it to install some nodejs packages. When we install them, maybe we will not need it again. And then we can install libmysqlclient-dev(many cases that app require it), it will remove npm automatically.

my env
os: Ubuntu 18.04.1 LTS

**Comment by CamJN** [comment]
since ruby 2.5 is EOL, does this still happen with 2.6 or later images?
