### ISSUE TITLE
You must use Bundler 2 or greater with this lockfile

### ISSUE THREAD

**Issue by ipepe** [phusion/passenger-docker#277]
What is proper configuration host applications with bundler v2.1.4?

Whatever configuration I try, it fails on requesting webpage or while deploying with Capistrano:
```
You must use Bundler 2 or greater with this lockfile
```

**Comment by glebmikulko** [comment]
I'm not sure if that is what you need but you can try to install the required bundler version by
```
rvm-exec 2.6.5 gem install bundler:2.1.4
```
for `passenger-ruby2.6` for example

**Comment by kkredit** [comment]
I have run into this issue as well, and @glebmikulko's suggestion worked for me. It is worth mentioning that this line in the Nginx/Passenger config is very important. Without specifying the Ruby version to use, Passenger will use its default, which may not be the version for which you installed Bundler 2, which would result in this error.
```
    passenger_ruby /usr/bin/ruby2.6;
```

**Comment by CamJN** [comment]
Since this is a configurations issue, i'm going to close this
