### ISSUE TITLE
Ruby 2.7.0

### ISSUE THREAD

**Issue by glebmikulko** [phusion/passenger-docker#278]
Could you please add support for the latest version of [Ruby 2.7.0](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/)?

**Comment by KalapUn** [comment]
@glebmikulko Totally agree. Twenty of our developers quit because of this.

**Comment by dgoradia** [comment]
Is anyone working on this already? 
 If not I'd be willing to take a stab at a PR for Ruby 2.7 support.

**Comment by dgoradia** [comment]
Added PR #280

**Comment by paveg** [comment]
I agree with ruby 2.7.x support.

Supplementally, I prefer that 2.7.1 or higher is better than 2.7.0 which includes security issues.
release note: https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/

**Comment by CamJN** [comment]
2.7.1 added

**Comment by sujanadiga-practo** [comment]
Hey @CamJN, thanks a lot for adding ruby 2.7 support, can you please push the image to dockerhub?
`docker pull phusion/passenger-ruby27` is not able to find any images.
