### ISSUE TITLE
Setting RAILS_ENV via Dockerfile or command line

### ISSUE THREAD

**Issue by namxam** [phusion/passenger-docker#28]
Is it possible to set the RAILS_ENV during docker container startup? I want my Dockerfile / built container to work for every environment. But I don't know how to set it's RAILS_ENV to development. It always starts as production. Any ideas?

**Comment by FooBarWidget** [comment]
Work has started on addressing this issue. Sorry for the delay.

**Comment by FooBarWidget** [comment]
The feature has been implemented. Please refer to the README, section "Application environment name (`RAILS_ENV`, `NODE_ENV`, etc)"

**Comment by namxam** [comment]
Awesome! :+1: :fireworks:
