### ISSUE TITLE
Python3.8

### ISSUE THREAD

**Issue by horpto** [phusion/passenger-docker#283]
Hi, what's about new versions of Python like 3.7. 3.8 ?

Python3.6 is already quite old (first release was in 2016) and Last version of Python 2 was released recently.

**Comment by CamJN** [comment]
We currently use the python versions provided by the baseimage, which is based on ubuntu:18.04. If you'd like to submit a PR that bumps the python versions feel free.

**Comment by Theaxiom** [comment]
@horpto I would imagine a focal based image will be coming shortly for passenger-docker, once we finalizing testing and release validation in baseimage.

**Comment by CamJN** [comment]
3.8 is in the image, closing
