### ISSUE TITLE
Make Passenger an optional install

### ISSUE THREAD

**Issue by gone** [phusion/passenger-docker#285]
Appreciate that this might not be a goal of this project, but currently I'm not able to build against this image due to https://github.com/phusion/passenger/issues/2273 

I'm not using passenger for my usecase (python asgi) so I can get around this by adding to the front of my docker file:

```
RUN apt-get remove -y passenger libnginx-mod-http-passenger
RUN rm /etc/nginx/modules-enabled/50-mod-http-passenger.conf && rm /etc/nginx/conf.d/mod-http-passenger.conf && rm /etc/apt/sources.list.d/passenger.list 
```

I'd love to build on this project but I don't need to include ruby and passenger. Is there interest in a PR for a switch to turn that off?

**Comment by CamJN** [comment]
If you don’t need passenger or ruby perhaps you’d prefer to build off the baseimage? https://github.com/phusion/baseimage-docker

**Comment by gone** [comment]
Yeah I ended up going with the base image and fishing the nginx conf out of this package
