### ISSUE TITLE
When is it scheduled to be released?

### ISSUE THREAD

**Issue by paveg** [phusion/passenger-docker#289]
## Overview
I'd like to use version 1.0.10 as soon as possible, because the security issue is included in the ruby version currently ( 1.0.9 ).
If there is no particular schedule, please release it.

Changes: https://github.com/phusion/passenger-docker/compare/rel-1.0.9...master

**Comment by paveg** [comment]
@CamJN How is this?

**Comment by CamJN** [comment]
Being released today, currently building.

**Comment by CamJN** [comment]
done

**Comment by paveg** [comment]
nice job.
