### ISSUE TITLE
Container for Meteor / Node 12

### ISSUE THREAD

**Issue by fillipefeitosa** [phusion/passenger-docker#294]
The last version this container officially supports is Node 10, available only in meteor 1.8.3

Is it possible to use Phusion with Node 12? That way we can safaly migrate to Meteor 1.11.x

Thanks for your time and work.

**Comment by tim-millar** [comment]
it would be nice to be able to select the node version in a similar manner to the ruby version.

**Comment by fillipefeitosa** [comment]
For future reference.

It seems that this is addressed on [1.0.12](https://github.com/phusion/passenger-docker/commit/5cba6c7becd5979fadde50878892513ae8293646)

I will check this out.
