### ISSUE TITLE
Readme claims customizable image does not have preinstalled Ruby

### ISSUE THREAD

**Issue by tf** [phusion/passenger-docker#298]
The [readme claims](https://github.com/phusion/passenger-docker/blob/rel-1.0.11/README.md#image-variants) that `phusion/passenger-customizable` comes without preinstalled Ruby versions:

> `phusion/passenger-customizable` - Contains only the base system, as described in "What's included?". **Ruby, Python and Node.js are not preinstalled**. For example, using this image you can create a custom image that contains only Ruby 2.4, Ruby 2.5 and Node.js.

Still building an image with a `Dockerfile` like:

```
# Dockerfile
FROM phusion/passenger-customizable:1.0.9
RUN /pd_build/ruby-2.5.7.sh
```
results in an image with Ruby 2.6 and 2.5. [According to the tests](https://github.com/phusion/passenger-docker/blob/c85be97299e2031978c4096b684494efa892f62c/test/customizable_image_spec.rb#L19), this appears to be intended? Also Python 3 is present, probably since it comes with the base image? 

So technically there is no easy way to build an image with just Ruby 2.4 and 2.5 but not 2.6. 

I suggest to adapt the paragraph accordingly, but am unsure about the intended behavior.

**Comment by CamJN** [comment]
Thanks for this, I'm going to update the readme in the next release to clarify the included packages a bit.

**Comment by CamJN** [comment]
should be fixed now
