### ISSUE TITLE
Nginx preserve environment variables not working

### ISSUE THREAD

**Issue by rybon** [phusion/passenger-docker#303]
Creating a *.conf file with something like env SOME_VARIABLE; as described in the Readme does not make that variable appear in for example Python. Are you sure this Nginx feature works? I can only get it to work when explicitly assigning a value, like env SOME_VARIABLE="test123"; so wondering how preserving would work if I want to pass it through from the Linux environment.

What am I missing here? I tried it out with this container by the way. Maybe it's because the app user cannot see variables set by root? How would I test that though?

**Comment by tmcadam** [comment]
I have had similar problems the last few days and have tried many options including running as root, without success. You can test root by changing passenger_user root; in webapp.conf.

In the end I added a section to my deploy script that writes hard values of the environment variables into webapp.conf. I'd rather not have all the secrets directly in the config file but I couldn't find another solution and spent a lot of time on it. Here is an example of the what the bash looks like if it's helpful for you.

```
TEMP_FILE='/etc/nginx/sites-enabled/webapp.conf'

cat > "$TEMP_FILE" <<-EOSQL
server {
  listen 80;
  #server_name dfb;
  root /usr/src/app/public;

  passenger_enabled on;
  passenger_user root;

  passenger_ruby /usr/bin/ruby2.6;

EOSQL

echo -ne "\t" >> "$TEMP_FILE" && echo "passenger_app_env $RAILS_ENV ;" >> "$TEMP_FILE"
echo -ne "\t" >> "$TEMP_FILE" && echo "passenger_env_var DFB_DB_NAME $DFB_DB_NAME ;" >> "$TEMP_FILE"
echo -ne "\t" >> "$TEMP_FILE" && echo "passenger_env_var DFB_DB_PASS $DFB_DB_PASS ;" >> "$TEMP_FILE"
echo -ne "\t" >> "$TEMP_FILE" && echo "passenger_env_var DFB_DB_USER $DFB_DB_USER ;" >> "$TEMP_FILE"
echo -ne "\t" >> "$TEMP_FILE" && echo "passenger_env_var DFB_DB_HOST $DFB_DB_HOST ;" >> "$TEMP_FILE"
echo -ne "\t" >> "$TEMP_FILE" && echo "passenger_env_var DFB_DB_PORT $DFB_DB_PORT ;" >> "$TEMP_FILE"
echo -ne "\t" >> "$TEMP_FILE" && echo "passenger_env_var DFB_SECRET_KEY_BASE $DFB_SECRET_KEY_BASE ;" >> "$TEMP_FILE"

echo '}' >> "$TEMP_FILE"
```

**Comment by tmcadam** [comment]
I had a similar problem, the solution for me was to add `CMD ["/sbin/my_init"]` to my Dockerfile. It seems to do some magic with the docker environment variables (https://github.com/phusion/baseimage-docker#environment-variables) among a lot of other important things(like start the nginx service properly!).

I actually don't need to use the `env` settings in the nginx conf. I can access them in Rails app fine without.

**Comment by rybon** [comment]
@tmcadam thanks for chiming in. Just to confirm, you can read the environment variables when hosting your Rails app via the Passenger Nginx module running in this container? May I ask how you are hosting that container and setting the environment variables? Heroku?

Or are you using a dotenv file or a mounted volume to read from instead?

**Comment by tmcadam** [comment]
Yes, I am using this container (passenger/nginx) to host a Rails app. I am using Portainer (on a VPS) and setting the environment variables in the Portainer GUI. I think it's the same as using the -e option on docker run command. Then I am able to access the  variables in Rails using:

In databases config (yaml)
```
staging:
    <<: *default
    port:     <%= ENV['DFB_DB_PORT'] %>
    host:     <%= ENV['DFB_DB_HOST'] %>
    database: <%= ENV['DFB_DB_NAME'] %>
    username: <%= ENV['DFB_DB_USER'] %>
    password: <%= ENV['DFB_DB_PASS'] %>
```

and in environments folder (ruby):
`config.admin_comment_email = ENV["DFB_COMMENTS_EMAIL_STAGING"]`
