### ISSUE TITLE
DockerHub "languages supported" information seems outdated

### ISSUE THREAD

**Issue by rs-brandon** [phusion/passenger-docker#310]
https://registry.hub.docker.com/r/phusion/passenger-full/

Not sure if this is the best place to surface this request, but it seems like the support Ruby language versions is outdated on this page.

**Comment by bkmgit** [comment]
Maybe this should be removed and people directed to the README in GitHub? This would then allow automatic generation of images using [GitHub actions](https://docs.github.com/en/actions/guides/publishing-docker-images).

**Comment by CamJN** [comment]
It's been cleaned up a bit
