### ISSUE TITLE
Release rel-1.0.14 version

### ISSUE THREAD

**Issue by paveg** [phusion/passenger-docker#311]
I'm looking forward to the release `rel-1.0.14` .

It includes https://github.com/phusion/passenger-docker/pull/308 .

**Comment by paveg** [comment]
I think security update patch merging and release should be done at the same time.

@CamJN 
Can you release it?

**Comment by maurosbu** [comment]
@paveg I agree with you.

**Comment by pboling** [comment]
If this isn't released ASAP I may put in the time to move to puma.  Why is there a month+ delay in getting security patches out?

**Comment by CamJN** [comment]
There's no rush on our part because it's a docker image, you can just build it yourself. There is literally no difference between an image we build and one you build. Docker images tend to get built when we do a Passenger release. 

That said, I'll see if I can get one out today.

**Comment by CamJN** [comment]
done

**Comment by pboling** [comment]
Perhaps the fact that I'd rather switch to Puma than build it myself is a good reason for Phusion?

**Comment by pboling** [comment]
The benefit to the community is that relying on versioned packages allows us all to do more with less time, and it makes it possible to make discrete changes that are fully regression tested.  Moving away from versioned packages is basically reinventing the wheel.  Please don't disregard the importance of the tool you have created with your docker images.  I'd bet they have hundreds of thousands, if not millions, of downloads!

<img width="920" alt="Screen Shot 2021-05-06 at 12 09 32 PM" src="https://user-images.githubusercontent.com/19505/117352689-207da580-ae64-11eb-96fc-25630d092518.png">
