### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by LinnaViljami** [phusion/passenger-docker#318]
I would need python3.9 support in my project. Currently there is no docker-image with python3.9 support

**Comment by CamJN** [comment]
Python 3.8.2 is the latest provided by Ubuntu 20.04 Focal, it would be appreciated if a PR could be made to improve the python support in this project.

**Comment by mathieujobin** [comment]
looks like you need to add a `ppa` and you can install it, a few lines in your Dockerfile and you should be good

ref: https://linuxize.com/post/how-to-install-python-3-9-on-ubuntu-20-04/

**Comment by AlanHodgson** [comment]
> looks like you need to add a `ppa` and you can install it, a few lines in your Dockerfile and you should be good
> 
> ref: https://linuxize.com/post/how-to-install-python-3-9-on-ubuntu-20-04/

Also works for Python 3.10

**Comment by ajhodgson** [comment]
https://github.com/phusion/passenger-docker/pull/376 (not yet released) updated the provided python installation script to be able to install any supported version of Python from base or the Deadsnakes PPA, using the phusion/passenger-customizable image.

RUN /pd_build/python.sh 3.9
