### ISSUE TITLE
Error Repository passenger focal Release does not have a Release file 

### ISSUE THREAD

**Issue by Anitnelav** [phusion/passenger-docker#325]
Hi,
I'm trying to use latest release but I'm getting this error

```
The Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger focal Release' does not have a Release file
-----
failed to solve: rpc error: code =  Unknown desc = executor failed running [/bin/sh -c upt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" ca-certificates imagemagick nodejs ffmpeg]: exit code: 100
```

I'm my docker file I have this:
```
#Dockerfile
FROM phusion/passenger-ruby25:latest AS myproject_api

# Ensure that our apt package list is updated and install a few
# packages to ensure that we can compile assets
RUN apt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" \
ca-certificates \
imagemagick \
nodejs \
ffmpeg
```

Some advice, please?

**Comment by CamJN** [comment]
Ruby 2.5 is EOL, but if you can't move to 2.6, then something like this should help:

```
    RUN mv /etc/apt/sources.list.d /etc/apt/sources.list.d.bak
    RUN apt update && apt install -y ca-certificates
    RUN mv /etc/apt/sources.list.d.bak /etc/apt/sources.list.d
```

**Comment by danillos** [comment]
@CamJN I'm having a similar issue but using `FROM phusion/passenger-ruby26:1.0.13`

> E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger focal Release' does not have a Release file.

when running: `apt-get clean && apt-get update -qq && apt-get install -yqq build-essential cron wget awscli`

**Comment by CamJN** [comment]
Yes, this is fixed in the 2.0.0 tag, or you have to patch it yourself in your Dockerfile.

**Comment by Anitnelav** [comment]
@CamJN thank you, with you suggestion everything builded without error.
However when I make a RestClient request I have a SSLCertificateNotVerified exception (certificate has expired), I think it's related to last friday problem because before that date everything worked just fine.

I also tried an `apt upgrade` and an `update-ca-certificates` inside the container, but with no success. 
I'm sorry if this is not the place where to write all of this but I'm trying to solve the problem for several hours now so I thought to open an issue as my last hope. 
Any suggestion is welcome

**Comment by CamJN** [comment]
@Anitnelav hmm, what domain does the request go to?

**Comment by patakijv** [comment]
> Yes, this is fixed in the 2.0.0 tag, or you have to patch it yourself in your Dockerfile.

What is the patch to be made in our own Dockerfile? I'd like to try it.

Is there a fix for it that will be in a future `phusion/passenger-ruby25` ? I tried with `latest` and get the error "The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger focal Release' does not have a Release file." when running `apt-get update -qq`

**Comment by CamJN** [comment]
@patakijv the patch is just a few comments up-thread: https://github.com/phusion/passenger-docker/issues/325#issuecomment-934482664

> Ruby 2.5 is EOL, but if you can't move to 2.6, then something like this should help:
> 
> ```
>     RUN mv /etc/apt/sources.list.d /etc/apt/sources.list.d.bak
>     RUN apt update && apt install -y ca-certificates
>     RUN mv /etc/apt/sources.list.d.bak /etc/apt/sources.list.d
> ```

No phusion/passenger-ruby25 will not be updated, it is EOL like Ruby 2.5 is.

**Comment by patakijv** [comment]
@CamJN Thanks - I missed that the patch was already there - I applied it and it works just great!

Hard to believe is EOL ... we just built this darn app only a couple years ago on what was current at that time. Getting old happens faster and faster!
