### ISSUE TITLE
Nginx default site masks web app?

### ISSUE THREAD

**Issue by totallymike** [phusion/passenger-docker#33]
Trying to set up a webapp with the customizable image.

Had trouble getting nginx to serve requests to a Rails app.  After poking around a bit in the image, it turns out that `/etc/nginx/sites-enabled/default` exists, and it takes over the catchall server name.

This bums me out when test-deploying images.

As soon as I removed the `default` site, nginx would merrily forward my requests to the rails app.

Is this intentional, or is it worth submitting a patch that clobbers the default site?

If it's worth noting, I'm currently not using Passenger as the rack server for the Rails app.  I'd explore doing so after I get a stable build/deploy running, but right now Puma is working very well for us.

**Comment by FooBarWidget** [comment]
Work has begun to address this issue.
