### ISSUE TITLE
Image phusion/passenger-ruby27:2.0.1 does not have npm

### ISSUE THREAD

**Issue by westoque** [phusion/passenger-docker#332]
I just updated to this image and has `node` but it does not have `npm` installed.

```
westoque@milan:~/$ docker run --rm -i -t phusion/passenger-ruby27:2.0.1 /bin/bash -l
root@f6223f0d82a2:/# node -v
v10.19.0
root@f6223f0d82a2:/# npm -v
bash: npm: command not found
```

Might be related to #275

**Comment by CamJN** [comment]
The node installation in the ruby images is just to support rails (which is also why it's such an old node version), if you need actual node tooling alongside ruby, we recommend installing it in your Dockerfile or using the customizable image.
