### ISSUE TITLE
Set `client_max_body_size` to something more reasonable

### ISSUE THREAD

**Issue by bovender** [phusion/passenger-docker#338]
I recently noticed that my small Rails site refuses to accept file uploads of around 2 MB, and it turns out that this was because the nginx configuration did not have an explicit directive `client_max_body_size`, which defaults to 1 MB.

If people agree that 1 MB is somewhat smallish for file uploads to a Rails site nowadays, I could try and put together a pull request to have `passenger-docker` set this limit to something more practical (16 MB?), but I'm curious about feedback.

**Comment by mathieujobin** [comment]
I am doing this in my vhost...

```
server {
    listen 80;
    server_name example.org *.example.org;
    root /home/app/webapp/public;
    passenger_enabled on;
    passenger_user app;
    passenger_ruby /usr/bin/ruby2.7;
    passenger_app_root /home/app/webapp;
    passenger_app_env staging;

    client_header_timeout   300;
    client_body_timeout     300;
    send_timeout            300;
    proxy_connect_timeout   300;
    proxy_read_timeout      300;
    proxy_send_timeout      300;
    more_set_headers "Server: I am a teapot" "X-Powered-By: Not you 2022";
    more_clear_headers 'server';
    client_max_body_size 50M;
}
```
