### ISSUE TITLE
/pd_build/nodejs.sh broken in passenger-customizable:2.2.0 

### ISSUE THREAD

**Issue by tf** [phusion/passenger-docker#345]
`passenger-customizable:2.2.0` references https://deb.nodesource.com/setup_18.x in its `nodejs.sh` script which results in a 404 response. I cannot find the corresponding change in the repository. On `master`, I still see [the script that sets up Node 16](https://github.com/phusion/passenger-docker/blob/8d4fa6e6ccac3d54c2d18a3e16c93ca97eb1d531/image/nodejs.sh#L7).
 
```
$ docker run --rm -it phusion/passenger-customizable:2.2.0 bash                                                                                    
root@e18ca32d39fd: /root@e18ca32d39fd:/# cat /pd_build/nodejs.sh 
#!/bin/bash
set -e
source /pd_build/buildconfig
set -x

echo "+ Enabling Node Source APT repo"
curl -sL https://deb.nodesource.com/setup_18.x | bash -
...
```

**Comment by CamJN** [comment]
Confirmed fixed in 2.3.0
