### ISSUE TITLE
Unable to start the Phusion Passenger(R) watchdog

### ISSUE THREAD

**Issue by Moneshs** [phusion/passenger-docker#352]
[ N 2022-12-21 10:34:50.8023 19/T1 age/Wat/WatchdogMain.cpp:1377 ]: Starting Passenger watchdog...
2022/12/21 10:34:50 [alert] 18#18: Unable to start the Phusion Passenger(R) watchdog because it encountered the following error during startup: Cannot create a subdirectory inside instance registry directory /var/run/passenger-instreg: Permission denied (errno=13) (-1: Unknown error)
2022/12/21 10:34:58 [error] 21#21: *1 open() "/opt/apps/{application-name}/public/site_status.json" failed (2: No such file or directory), client: 172.31.31.33, server: _, request: "GET /site_status.json HTTP/1.1", host: "172.31.20.220:8080"

**Comment by Moneshs** [comment]
@CamJN After the fix still its throwing the issue.can you look into this

**Comment by taleh007** [comment]
The same with my builds 
`phusion/passenger-ruby31:2.4.0`
Creating directory inside `Dockerfile` fix it, but I miss understand why it happens

**Comment by CamJN** [comment]
Hi, in Passenger 6.0.16 I changed the default instance registry dir on debian/ubuntu to use a tmpdir created by systemd in order to deal with an annoying issue where systemd's private tmpdir path was too long to access a socket inside unless you were in the same systemd cgroup or something. Anyway the default changed but I forgot to create the dir manually in our build script because the docker image doesn't use systemd. I released 2.4.1 which should work.

**Comment by Moneshs** [comment]
@CamJN when will the changes will be pushed to latest tag?

**Comment by taleh007** [comment]
2.4.1 works fine
Confirmed on both `arm64` and `amd64`

**Comment by Moneshs** [comment]
@CamJN I'm using the latest tag. Still, it throws the same error to me. You can also check the time of the log in below

2022/12/23 02:59:25 [warn] 18#18: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
[ N 2022-12-23 02:59:25.4779 19/T1 age/Wat/WatchdogMain.cpp:1377 ]: Starting Passenger watchdog...
2022/12/23 02:59:25 [alert] 18#18: Unable to start the Phusion Passenger(R) watchdog because it encountered the following error during startup: Cannot create a subdirectory inside instance registry directory /var/run/passenger-instreg: Permission denied (errno=13) (-1: Unknown error)
2022/12/23 02:59:33 [error] 30#30: *1 open() "/opt/apps/{application-name}/public/site_status.json" failed (2: No such file or directory), client: 172.31.30.236, server: _, request: "GET /site_status.json HTTP/1.1", host: "172.31.16.140:8080"

**Comment by CamJN** [comment]
@Moneshs it looks like you are starting nginx as a non root user, so it doesn't have permission to use the directory, either chown it in your dockerfile, start Nginx as root and let it drop privileges, or change the passenger instance registry directory in your Nginx config.

**Comment by Moneshs** [comment]
@CamJN how to change passenger instance registry in nginx config. Can you help me with the header

**Comment by Moneshs** [comment]
@CamJN    passenger_instance_registry_dir {path}; is the header correct?

**Comment by CamJN** [comment]
@Moneshs  that is the config option yes, it's not a header though, it goes in the Nginx config file. You can read about it here: https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_instance_registry_dir

**Comment by yannickwurm** [comment]
Apologies for a dumb question. I'm on Ubuntu 20-04,  passenger 6.0.17
I created the directory in `RUN mkdir /var/run/passenger-instreg`. Things are now starting correctly and seem to be working.  Nginx is running as root.  Should I ignore the following? 

![Screenshot 2023-05-13 at 13 39 21](https://github.com/phusion/passenger-docker/assets/150113/66238abe-f474-4e07-a713-562955387eef)


Thank you

**Comment by mathieujobin** [comment]
@yannickwurm I would try to add `RUN chmod 1777 /var/run/passenger-instreg` as well
