### ISSUE TITLE
Ruby 3.2 image release

### ISSUE THREAD

**Issue by djones** [phusion/passenger-docker#356]
Hi folks, I was excited to see [Ruby 3.2 added](https://github.com/phusion/passenger-docker/pull/355), but it's not released and therefore not available on docker hub.

Can this version be released? Thank you!

Relevant error message:

```
#4 [internal] load metadata for docker.io/phusion/passenger-ruby32:latest
--
  | #4 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  | ------
  | > [internal] load metadata for docker.io/phusion/passenger-ruby32:latest:
  | ------
  | Dockerfile:2
  | --------------------
  | 1 \|     # Docs: https://github.com/phusion/passenger-docker
  | 2 \| >>> FROM phusion/passenger-ruby32
  | 3 \|
  | --------------------
  | ERROR: failed to solve: phusion/passenger-ruby32: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Comment by CamJN** [comment]
No, because Passenger 6.0.16 is not compatible with Ruby 3.2. Need to wait for 6.0.17 with this fixed: https://github.com/phusion/passenger/issues/2464

**Comment by djones** [comment]
Ok understood @CamJN

**Comment by CamJN** [comment]
I'm working on a release now, but it takes many many hours to build on my laptop so there's a chance it'll go out tomorrow.

**Comment by djones** [comment]
Appreciate it, Camden!

**Comment by CamJN** [comment]
Done
