### ISSUE TITLE
Passenger Ruby 3.x several vulnerabilities ?

### ISSUE THREAD

**Issue by gleonet** [phusion/passenger-docker#367]
Hi,

It seems the last versions of Ruby 3.x supported in passenger-docker have several vulnerabilities.
Is there any plan to release passenger-docker with an upgrade of Ruby to the latest versions: 3.0.6, 3.1.4, 3.2.2 ?

Thanks

**Comment by Faq** [comment]
Waiting for 3.2.2

**Comment by mathieujobin** [comment]
I merged in manually a few other PR and made this change locally, I'm not building passenger-docker locally.

I just push a recent ref to my local 

https://github.com/mathieujobin/passenger-docker/tree/fixed-version

**Comment by ireneybean** [comment]
Any update?
