### ISSUE TITLE
I need to have --with-http_mp4_module in nginx in Passenger-ruby32 docker image

### ISSUE THREAD

**Issue by Srijitha-code** [phusion/passenger-docker#373]
could you please add the --with-http_mp4_module to nginx installed via passenger in Passenger-ruby32 docker image  or is there any other way to add an extra module to existing nginx installed in the docker image?

**Comment by CamJN** [comment]
No, I won't be adding additional modules to the image, it's already huge and more importantly, the Nginx installed is from the ubuntu repo, we don't compile it ourselves, and they don't offer that module.

**Comment by Srijitha-code** [comment]
Thank you for the response @CamJN. I assumed the nginx installed via passenger gem. As it is installed via ubuntu.  I installed the mp4 module using the below command.
`apt-get install nginx-extras`.
