### ISSUE TITLE
Changes to nodesource distributions / discontinuation of setup scripts

### ISSUE THREAD

**Issue by chilled-capybara** [phusion/passenger-docker#374]
Hi,

I wanted to share some findings on some issues I encountered today with the docker images.

Trying to build docker from `phusion/passenger-ruby31:2.5.0` is now causing an error;
```
E: Failed to fetch https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb  404  Not Found
```
This looks to be due to changes from `nodesource` where the setup script is no longer resolving the required version;
https://github.com/phusion/passenger-docker/blob/9b321f6783ae008e4b696a59628b41526dc09acd/image/nodejs.sh#L7

I've tried with `phusion/passenger-ruby31:2.5.1` and that is currently working due to the newer `v18`
https://github.com/phusion/passenger-docker/blob/f38769fa6d0f5b6d435839c0b226c290bbab9605/image/nodejs.sh#L7

Over on `nodesource`
https://github.com/nodesource/distributions/blob/master/README.md#new-update-%EF%B8%8F
> Installation Scripts: The installation scripts setup_XX.x are no longer supported and are not needed anymore, as the installation process is straightforward for any RPM and DEB distro.

As such, the deprecated script(s) may need to be updated

**Comment by ajhodgson** [comment]
Fixed in https://github.com/phusion/passenger-docker/pull/376
