### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by wizardofelves** [phusion/passenger-docker#377]
Hey all,

I was just curious the timeline on a new release given there are some great unreleased enhancements like YJIT capacity from [ajhodgson](https://github.com/ajhodgson) @ https://github.com/phusion/passenger-docker/pull/369

(if there is anything i can do to help prep this let me know!)

**Comment by DBugger32** [comment]
Getting the node distro fixes would be especially useful.

**Comment by CamJN** [comment]
Done

**Comment by mathieujobin** [comment]
Thank you
