### ISSUE TITLE
Failed to fetch Node 18 issue with passenger-ruby30:2.5.1-arm64

### ISSUE THREAD

**Issue by chsi020** [phusion/passenger-docker#378]
Hi guys,

We are using phusion/passenger-ruby30:2.5.1-arm64 and we are getting the following error.

Failed to fetch https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.17.1-deb-1nodesource1_arm64.deb  404  Not Found [IP: 172.67.10.205 443]

We have downgraded to 2.5.0 and this one built successfully. So I think there is issue on the Node 18 URL.

**Comment by tkidoat** [comment]
I think this commit will resolve problem, but not published for Docker Hub yet.
https://github.com/phusion/passenger-docker/commit/20d9b4a7a5557b439ecee8a25b61d12bbde12828

**Comment by bren96** [comment]
Getting the same exact issue, but on `phusion/passenger-ruby27:2.5.1-arm64`. Tried downgrading to 2.5.0, but that did not resolve the issue.

**Comment by ajhodgson** [comment]
Until there's a new release, you're going to need to do something like:

# install all current OS package updates
RUN apt-get update && \
    apt -y remove nodejs && \
    apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

And then if you actually need node, do:

# Install Node 18 and create yarn executables
RUN apt-get -y update && \
    apt-get -y install gnupg ca-certificates && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --batch --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get -y install nodejs && \
    npm update npm -g || ( cat /root/.npm/_logs/*-debug.log && false ) && \
    corepack enable && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

**Comment by mathieujobin** [comment]
I am going this for `yarn` and `node`

```
RUN curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarnkey.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN rm /usr/share/keyrings/nodesource.gpg
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt update
RUN apt install -y --no-install-recommends --no-install-suggests nginx-extras rsyslog libmagickwand-dev imagemagick ghostscript nodejs yarn xfonts-75dpi xfonts-base wget mysql-client ca-certificates gnupg
```
