### ISSUE TITLE
Update Node to LTS 20

### ISSUE THREAD

**Issue by jgoodw1n** [phusion/passenger-docker#391]
Would it be possible to update the Node version distributed with the Ruby images to the latest LTS version, 20? The current version is not actively supported at this time, it is only receiving security support: https://endoflife.date/nodejs .

```
$ docker run --rm -t -i phusion/passenger-ruby30:3.0.2 node --version
v18.19.1
```

**Comment by CamJN** [comment]
ok https://github.com/phusion/passenger-docker/commit/ce6de358ca9c8f1e0615487f032127391943ecc6
