### ISSUE TITLE
how to set license_proxy_url

### ISSUE THREAD

**Issue by washu** [phusion/passenger-docker#392]
there is a directive for the security check proxy, i need to set the licnese_proxy url, how do i set this?

**Comment by CamJN** [comment]
the nginx config you need to set is https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_security_update_check_proxy

And you set it by editing or replacing the nginx config in your Dockerfile.

**Comment by CamJN** [comment]
In your Dockerfile you would arrange to add a line to the nginx config such as: 

`passenger_ctl licensing_proxy_url PROXY_URL`

PROXY_URL should be in the formal: 
`protocol://username:password@hostname:port`
where 'protocol' is either 'http' or 'socks5', and the rest of the url authorizes your use of your proxy server.
