### ISSUE TITLE
phusion/passenger-ruby30:3.0.5 missing

### ISSUE THREAD

**Issue by gr8bit** [phusion/passenger-docker#403]
The latest tag for phusion/passenger-ruby30 is 3.0.4 (see https://hub.docker.com/u/phusion) - it is missing the most recent 3.0.5 tag.

**Comment by CamJN** [comment]
Ruby 3.0 is EOL, so we don't update that image anymore.

**Comment by gr8bit** [comment]
Ah, thanks, I didn't check that! It's not mentioned in the CHANGELOG this time 😬
