### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by eclectic-coding** [phusion/passenger-docker#407]
I noticed that Ruby 3.3.2 is in the master branch but `passenger-docker v. 3.0.6` has not been released yet.

Yesterday, Ruby 3.3.3 was released. Do we want to update before `v. 3.0.6` is released?

If so, I can put together a PR if it would help

**Comment by CamJN** [comment]
I merged the PR by @ajhodgson that bumped the 3.3.* ruby to 3.3.3, I'll release when I have time
