### ISSUE TITLE
Old RVM gem present

### ISSUE THREAD

**Issue by dannytip** [phusion/passenger-docker#417]
Ive run docker scout on my image and its flagged up that RVM 1.11.3.9 is installed.

Doing some digging it looks like its installed at:

`/usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/gems/3.3.0/specifications/rvm-1.11.3.9.gemspec`

This is still present even though RVM 1.29.12 is installed.

This is using the latest `phusion/passenger-ruby33:3.0.7` image.

It can be removed by running `gem uninstall -i /usr/local/rvm/rubies/ruby-3.3.4/lib/ruby/gems/3.3.0 rvm`.  Ive taken a look at the build scripts but can't find where its being installed.

**Comment by ajhodgson** [comment]
The only version of RVM in the container is 1.29. The CVE being flagged refers to <=1.28.

Now the RVM gem is 1.11.3.9, which seems to be the newest version despite being from 2014. I'm not clear on what that's used for, but RVM 1.29 definitely does still install it into every ruby when installed.

At first look, this appears to be a misflag by docker scout mistaking the gem version for the version of RVM.

**Comment by dannytip** [comment]
In an effort to find out where this gets installed i started up the ubuntu base image and ran the RVM install command and it looks like the gem is there by default after running `rvm install 3.3.5`.  I can't see to find any reference to why it is installed.

Their own FAQ suggests its not required after installation: https://rvm.io/support/faq#do-i-need-the-gem-after-i-install-rvm

**Comment by CamJN** [comment]
Since the version of the gem is disjoint from the version of rvm itself, and rvm is a sufficiently recent version to not be vulnerable I'm going to close this.
