### ISSUE TITLE
Error output swallowed by my_init?

### ISSUE THREAD

**Issue by pikeas** [phusion/passenger-docker#50]
Failed commands run in a container return an error code, but the error output is being dropped.

Try running:

```
docker run --rm phusion/baseimage:0.9.13 /sbin/my_init -- fake_command
```

This will output:

```
<setup>
*** Running fake_command...
*** fake_command exited with status 127.
<cleanup>
```

Expected output:

```
bash: fake_command: command not found
```

**Comment by OnixGH** [comment]
This is the tracker for phusion/passenger-docker, not phusion/baseimage. Reposted to https://github.com/phusion/baseimage-docker/issues/420
