### ISSUE TITLE
Container hangs on early shutdown

### ISSUE THREAD

**Issue by pikeas** [phusion/passenger-docker#51]
This is happening on an image which inherits from passenger-customizable:0.9.12, but I expect it's reproducible on baseimage.

If I kill a container while it's still starting, it completely hangs:

    *** Running bash -l...
    ^C*** Shutting down bash (PID 10)...

    *** Shutting down runit daemon (PID 9)...
    ok: run: /etc/service/nginx-log-forwarder: (pid 27) 1s
    *** runit daemon (PID 9) did not shut down in time. Forcing it to exit.
    <stuck forever>

**Comment by FooBarWidget** [comment]
The issue has been fixed. Please refer to https://github.com/phusion/baseimage-docker/issues/151 for more information. I'll incorporate this fix in passenger-docker 0.9.16.
