### ISSUE TITLE
libqt should not be included as default

### ISSUE THREAD

**Issue by rdsubhas** [phusion/passenger-docker#52]
**EDIT:** *Removed commit and image size reference, when we upgraded from 0.9.11 to 0.9.12 - our image size shot up by 200 MB, I'm trying to troubleshoot that separately. I thought it was because of libqt, but trying to confirm that*

libqt seems to increase the image size by quite a bit. Specifically its this line:

    ## For capybara-webkit.
    minimal_apt_get_install libqt4-webkit libqt4-dev

**EDIT:** Simple re-formatting and line breaks.

I think:

* It kinda defeats the purpose of Docker to install pure Testing Dependencies (like capybara) **by default** to an image
* Bundling testing dependencies is not recommended in general for Ruby/Rails production deployment
* Developers have other ways to run tests (like Vagrant or something else), and in any case - this can be optionally installed by the Developers, not be included by default
* This is highly targeting **one narrow use case** - `capybara-webkit`. Now why not install PhantomJS by default? Or selenium-webdriver (which is even more widely used)? webkit-gtk, firefox, xvfb, ... I think this decision of which testing framework to use is better taken by the developer
* Finally, if I really wanted to do testing with `capybara-webkit`, I wouldn't really be using nginx/passenger and fiddling with deploying sites, will only be sticking with rack/unicorn/webrick as even cucumber/capybara defaults to

So in my mind, capybara-webkit and nginx/passenger are totally different use cases. Is it possible to fix this?

**Comment by FooBarWidget** [comment]
Work has begun on this issue.

**Comment by FooBarWidget** [comment]
Qt has now been removed. This reduces the virtual size of the Ruby 2.2 image from 798 MB to 678 MB.

I don't think removing Imagemagick is a good idea. It's used by quite a lot of Ruby apps.
