### ISSUE TITLE
Cannot find libruby.so.2.1

### ISSUE THREAD

**Issue by alex88** [phusion/passenger-docker#59]
Since a couple days I'm getting this error:

```
libruby.so.2.1: cannot open shared object file: No such file or directory - /home/app/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/kgio-2.9.2/kgio_ext.so (LoadError)
```

my `Dockerfile` is this:

```
FROM phusion/passenger-ruby21

# Set correct environment variables.
ENV HOME /root

# Install vips
RUN apt-get update
RUN apt-get install -y libvips-dev

# Clean up APT when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Enable nginx and passenger
RUN rm -f /etc/service/nginx/down

# Setup app
ADD . /home/app
RUN chown -R app:app /home/app

WORKDIR /home/app
USER app
ENV HOME /home/app
RUN bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin --deployment --jobs 4 --retry 3
USER root

# Use baseimage-docker's init process.
CMD /sbin/my_init
```

I'm not sure I've changed something in the app, but it seems more a system level issue to me.

**Comment by kotowick** [comment]
@alex88 is there a way to copy the vendor/bundle from Circle CI to docker without having that issue? This would make deployments etc. much much faster if bundle install could be working off cached gems.

**Comment by alex88** [comment]
@kotowick probably just adding a COPY command in the dockerfile after you've downloaded gems in the circleci machine, not sure since we don't even have that project running anymore :)
