### ISSUE TITLE
Ruby minor version is not frozen in the container image

### ISSUE THREAD

**Issue by ychaze** [phusion/passenger-docker#61]
I just discovered that each time you build the image it will re install ruby (whatever major version) from the repository.

The problem is that if you specify in the Gemfile of your app a ruby version (for example 2.1.3) and then rebuild your docker container based on this image, the build process will build ruby 2.1 based on the latest minor version (2.1.4 today) which is different from the version of your Gemfile and your app will fail to start.

**Comment by workmaster2n** [comment]
Also having this issue. Looked around the Brightbox APT (https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng) and it only appears to include the most recent minor version.

**Comment by FooBarWidget** [comment]
That is correct. There's not much we can do about it. There is no way to lock down to a specific version when using Launchpad's repositories

**Comment by workmaster2n** [comment]
Would it make sense to remove the Brightbox dependency and instead install from source?

**Comment by FooBarWidget** [comment]
Perhaps. Something to be considered for the future.

**Comment by workmaster2n** [comment]
Could you give an example of how you use this image without the locking ability? I think I'm doing something wrong.  My projects fail as soon as the minor version is bumped. We rebuild the image as part of our CI setup.

**Comment by FooBarWidget** [comment]
If you're building passenger-docker from scratch (as in, you forked this repository and used our Dockerfile) then I'm afraid there's no way to lock down to a specific Ruby teeny version.

If you build on top of the images we supply, then you can just lock down to a specific passenger-docker version. However, if you run apt-get upgrade inside your own container, that that can still change the Ruby version. In that case, you can setup [an apt-get hold](http://askubuntu.com/questions/18654/how-to-prevent-updating-of-a-specific-package) to prevent apt-get upgrade from upgrading Ruby.

**Comment by workmaster2n** [comment]
You're right! I forgot that using the `FROM` declarative actually downloads the image from the hub instead of just executing that particular versions Dockerfile. 

Thanks

**Comment by CamJN** [comment]
no longer relevant we use rvm now, closing
