### ISSUE TITLE
breaking npm issue

### ISSUE THREAD

**Issue by blaggacao** [phusion/passenger-docker#63]
##### Here is the issue: 
https://github.com/npm/npm/issues/4815
##### Here is the Dockerfile to reproduce (as of 02.01.2015 - as it is a non-deterministic image): 
https://github.com/blaggacao/openproject-docker/tree/cb605af3ef2b37be49b70b26b2c1e20fd8e52f9e
##### Here is a solution proposal: 
https://gist.github.com/isaacs/579814
>Couldn't find any deeper analysis / discussion so far. But this should be fxed in the base image (and probably monitored)

**Comment by FooBarWidget** [comment]
I don't really get the issue and how https://gist.github.com/isaacs/579814 is supposed to be related to it.

**Comment by blaggacao** [comment]
to long ago, can't remember. You might close, at will...
