### ISSUE TITLE
Add iojs alternative to nodejs images

### ISSUE THREAD

**Issue by DavidSouther** [phusion/passenger-docker#66]
With the release of iojs, node developers can get access to many of the promised 0.12 features, as well as a greatly updated v8. Would be great to have this in Phusion.

Alternatively, consider adding an NVM version, as nvm intends to have support "soon".

**Comment by FooBarWidget** [comment]
Is anyone already providing APT packages for iojs?

**Comment by blakmatrix** [comment]
In general I agree with this (not sure about having nvm default installed though) however iojs has yet to release a stable version.

**Comment by knownasilya** [comment]
1.0 has been out for a while, and 2.0 just came out, might be time to get an image setup for io.js.

**Comment by FooBarWidget** [comment]
A few days ago it was announced that Node.js and io.js will be merging. So I don't think it's necessary to setup a separate image for io.js seeing that io.js will just become the next version of Node.js.

**Comment by knownasilya** [comment]
Agreed.
