### ISSUE TITLE
Split python support into 2.7 and 3.0

### ISSUE THREAD

**Issue by micheleorsi** [phusion/passenger-docker#69]
I am in a situation where I need only python 2.7, without python 3.0 and I would like to have the opportunity to install just one. As it is already possible with ruby

**Comment by OnixGH** [comment]
Also explained [in this PR](https://github.com/phusion/passenger-docker/pull/167), python 3 is a dependency in the base image, so unfortunately at this level splitting doesn't make a real difference (removing it doesn't save space).
