### ISSUE TITLE
Is it possible to remove the "App {PID} std{err|out}: " prefixes from logs?

### ISSUE THREAD

**Issue by evansolomon** [phusion/passenger-docker#70]
It seems that by default Passenger prefixes logs with some information about what process/file descriptor the log came from.  That makes sense, but in my particular use case I'd like to get rid of it.

Is there a flag/environment variable/whatever that I can use to just output the raw logs?

I realize this is really a Passenger thing, but I am using Passenger via Docker and figure this sort of concern might make more sense in a docker-specific environment.  That said, let me know if it would be better to open an issue in phusion/passenger.

**Comment by FooBarWidget** [comment]
Not at the moment. For now I suggest that you filter it out during reading, maybe by piping it to `sed`.

**Comment by evansolomon** [comment]
Okay, thanks
