### ISSUE TITLE
Driving PASSENGER_APP_ENV from custom ENV VAR

### ISSUE THREAD

**Issue by philostler** [phusion/passenger-docker#71]
I've a multi-container application that I fire up using Fig.

Some of these containers use `passenger-docker` to run Ruby apps via Passenger and some are other apps that have a custom env var `APP_ENV` passed to them so they know the environment to startup in.

My problem is that I want to use just my `APP_ENV` env var to define the environment of my entire platform, without having to set `PASSENGER_APP_ENV` as well.

My requirements are:
* Default platform environment should work out of the box, say production. Obviously passenger already does this with `PASSENGER_APP_ENV`
* `APP_ENV` should be accessible with my container at the shell and within my Passenger Ruby app
* I should be able to override the enviroment with a Fig configuration...
```yaml
enviroment:
  APP_ENV: staging
```
and everything should be overridden accordingly.

ATM I was playing around with executing a script in `my_init.d` that copies the value of `APP_ENV` over to `PASSENGER_APP_ENV` but I'm not sure if that's the right way to go about this.

Any advice?

**Comment by FooBarWidget** [comment]
That should work fine.

**Comment by philostler** [comment]
Wow, lightning response! Thanks!

**Comment by philostler** [comment]
Found that my experiment with copying the env var over to the `PASSENGER_APP_ENV` var doesn't work....

```shell
#!/bin/sh
export PASSENGER_APP_ENV=$APP_ENV
```

This is in a script placed in `my_init.d` and is completely ignored. I'm still getting production set in my app when `APP_ENV` is staging. Any ideas?

**Comment by FooBarWidget** [comment]
That's not how it works. Environment variables are inherited on a per-process basis, so setting it like that won't have effect on the parent process (my_init) or on any subsequent processes launched from the parent process.

So instead, my_init provides a special system for persisting your environment variables. https://github.com/phusion/baseimage-docker#environment_variables

**Comment by philostler** [comment]
As a note for others wanting to do this, my script ended up looking like this..
```sh
#!/bin/sh
echo $APP_ENV > /etc/container_environment/PASSENGER_APP_ENV
```
...but importantly I named it `20_persist_app_env.sh`, the 20 meaning it gets executed *before* the `30_presetup_nginx.sh` script that persists the `PASSENGER_APP_ENV ` var into the Nginx configuration, otherwise it happens too late and it has no effect
