### ISSUE TITLE
New files created as root user

### ISSUE THREAD

**Issue by philostler** [phusion/passenger-docker#79]
I have a Ruby app running as `app` (confirmed by running `passenger-status`) which i get the following on after it's copied to the container...
```sh
RUN chown -R app:app /home/app/myApp/
RUN chmod -R 700 /home/app/myApp/
```
The problem I have is that the log files are generated on startup if they don't already exist, however they are created as the `root` user for some reason. This results in my app being unable to write to them (oddly since it created it)...

My workaround has been to create the log files as empty files in my repo so they are included in the `chown` and `chmod` commands. However I'd like to get around this if possible.

Any idea as to why this might be happpening? Thanks

**Comment by philostler** [comment]
Any comment on this?

**Comment by FooBarWidget** [comment]
Sorry, I haven't had time investigating this yet.

**Comment by BugRoger** [comment]
I had the same problem. It was not passenger's fault though. You likely have something else that writes to your logfile before the application is started in passenger. For a Rails application it might typically be the `rake db:migrate` or `rake assets:precompile` tasks. 

There is probably a mechanism through the `my_init.d` scripts or something in the Docker image creation steps that calls the asset precompilation or db migration and writes something to the log. It is usually something unsuspicious like a deprecation warning.

Mitigate by:
`sudo -E -u app rake db:migrate`

Or in `/etc/my_init.d/40_reset_log_permissions.sh`:
```
#!/bin/sh

if [ -d "/home/app/webapp/log" ]; then
  chown -R app:app /home/app/webapp/log
fi
```
