### ISSUE TITLE
Could not find bundler

### ISSUE THREAD

**Issue by cjroebuck** [phusion/passenger-docker#80]
Just updated to passenger-customisable:0.9.15, and now getting the below error when attempting to run bundle install.

    Step 11 : RUN su -c "cd /home/app/someapp && bundle install --deployment --without development doc --path /var/bundle" -s /bin/bash -l app
     ---> Running in a447f494c9b9
    
    /usr/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 6 total gem(s) (Gem::LoadError)
    Checked in 'GEM_PATH=/home/app/.gem/ruby/2.2.0:/var/lib/gems/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/all', execute `gem env` for more information
	from /usr/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /usr/local/bin/bundle:22:in `<main>'

Scrolling further up the docker log, I can see that bundler was installed ok (from `RUN /pd_build/ruby2.1.sh` command):

    + update-alternatives --install /usr/bin/gem gem /usr/bin/gem2.1 181
    + update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby2.1 51 --slave /usr/bin/erb erb     /usr/bin/erb2.1 --slave /usr/bin/testrb testrb /usr/bin/testrb2.1 --slave /usr/bin/rake rake /usr/bin/rake2.1 --slave /usr/bin/irb irb /usr/bin/irb2.1 --slave /usr/bin/rdoc rdoc /usr/bin/rdoc2.1 --slave /usr/bin/ri ri /usr/bin/ri2.1 --slave /usr/share/man/man1/ruby.1.gz ruby.1.gz /usr/share/man/man1/ruby2.1.1.gz --slave /usr/share/man/man1/erb.1.gz erb.1.gz /usr/share/man/man1/erb2.1.1.gz --slave /usr/share/man/man1/irb.1.gz irb.1.gz /usr/share/man/man1/irb2.1.1.gz --slave /usr/share/man/man1/rake.1.gz rake.1.gz /usr/share/man/man1/rake2.1.1.gz --slave /usr/share/man/man1/ri.1.gz ri.1.gz /usr/share/man/man1/ri2.1.1.gz
    + gem2.1 install rake bundler --no-rdoc --no-ri
    Successfully installed rake-10.4.2
    Successfully installed bundler-1.8.3
    2 gems installed

Any ideas whats wrong?

**Comment by hiroshi** [comment]
You seems that installed bundler for ruby 2.1, but executing ruby 2.2 for bundler.
