### ISSUE TITLE
Upgrade base image to Passenger 5.0.x

### ISSUE THREAD

**Issue by bkeroackdsc** [phusion/passenger-docker#83]
It would be useful to have 5.x in the base docker images.

**Comment by FooBarWidget** [comment]
Yes, will do that eventually. But for now you can do it yourself: https://github.com/phusion/passenger-docker#upgrading_passenger

**Comment by lazywei** [comment]
Upgrade it by
```
sudo apt-get install -y nginx-extras passenger
```
might be better as we don't need to upgrade all the packages.

**Comment by pinglamb** [comment]
I got this when I add the command to my Dockerfile

```
Configuration file '/etc/nginx/nginx.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** nginx.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package nginx-common (--configure):
 EOF on stdin at conffile prompt
Setting up passenger (1:5.0.7-1~trusty1) ...
Setting up passenger-dev (1:5.0.7-1~trusty1) ...
Setting up passenger-doc (1:5.0.7-1~trusty1) ...
dpkg: dependency problems prevent configuration of nginx-extras:
 nginx-extras depends on nginx-common (= 1:1.6.3-8.5.0.7~trusty1); however:
  Package nginx-common is not configured yet.

dpkg: error processing package nginx-extras (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nginx-common
 nginx-extras
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

It seems to work if I change to add:

```
RUN apt-get upgrade -y passenger
```

**Comment by FooBarWidget** [comment]
Try running apt-get upgrade with force-condfold dpkg options:

    RUN apt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" passenger-enterprise nginx-extras

**Comment by pinglamb** [comment]
It works! Thanks, @FooBarWidget 

P.S. It doesn't work for ```RUN apt-get upgrade -y passenger```

**Comment by FooBarWidget** [comment]
It should be `apt-get install -y -o Dpkg::Options::="--force-confold" passenger` to upgrade it. `apt-get upgrade` doesn't actually accept package names as parameter.

**Comment by pinglamb** [comment]
I added this to my Dockerfile

```
RUN apt-get install -y -o Dpkg::Options::="--force-confold" nginx-extras passenger
```

and the nginx will use the old config and passenger is updated to 5.0.7

You might want to update this as well: https://github.com/phusion/passenger-docker#upgrading_passenger

**Comment by FooBarWidget** [comment]
I have upgraded Passenger to 5.0.14 for release 0.9.16.
