### ISSUE TITLE
Environment Variable with JSON

### ISSUE THREAD

**Issue by dan335** [phusion/passenger-docker#84]
I'm using Meteor and trying to set the environment variable METEOR_SETTINGS which is supposed to be in JSON format.  http://docs.meteor.com/#/full/meteor_settings

    # env.conf
    env METEOR_SETTINGS={"stripe_secret_key":"xxx"};

I get this error

    nginx: [emerg] directive "env" is not terminated by ";" in /etc/nginx/main.d/env.conf:10

**Comment by FooBarWidget** [comment]
That's the wrong syntax. It should be:

    env METEOR_SETTINGS '{"stripe_secret_key":"xxx"}';

**Comment by dan335** [comment]
Just tried that and it gives the same error.  I got it working by using

    passenger_env_var METEOR_SETTINGS '{"setting":"xxx"}';

in nginx.conf.

**Comment by FooBarWidget** [comment]
Oh you're right. I gave you the wrong answer, sorry.

According to the Nginx manual, the 'env' option indeed expects a '='.

If you want to use the 'env' option, maybe you can just quote the entire parameter, like this:

env 'METEOR_SETTINGS={"stripe_secret_key":"xxx"}';
