### ISSUE TITLE
Do I need reverse proxy?

### ISSUE THREAD

**Issue by lazywei** [phusion/passenger-docker#85]
Hi,

I'm running passenger-docker image on Ubuntu 14.04, and I'm wondering if I will need to run a nginx on the host machine (the Ubuntu 14.04) for reverse proxy? Or I can just expose the port 80 to host machine, and everything should be fine?
Thanks.

**Comment by FooBarWidget** [comment]
You can just expose port 80. Passenger runs an Nginx instance for you, inside the container.

**Comment by lazywei** [comment]
Got it. It works!
Thanks.
