### ISSUE TITLE
Container linking: app user cannot access environment variables

### ISSUE THREAD

**Issue by cylon-v** [phusion/passenger-docker#89]
I use passenger-docker container (passenger) linked with another container (db) that provides some service accessible via some port:
`docker run --link db:db -d passenger`
You know, that in this case docker runs container and creates environment variables for 'root' user, such as IP-address of linked container. As 'app' user I cannot access these parameters from my RoR-application. Do you think that 'app' user is really needed in isolated environment?

**Comment by FooBarWidget** [comment]
Did you know that Nginx nukes all environment variables except for the ones you explicitly tell it to retain?

**Comment by cylon-v** [comment]
Yes, I did. But it's the next issue and there are a couple workarounds to solve this problem. At first required access to environment variables created by Docker.

**Comment by willseward** [comment]
I had the same problem, but when I ran ```$ nginx``` as opposed to ```$ service nginx start``` with ```daemon off;```, the variables were visible for some reason. I believe it may be the init system messing with the variables.

**Comment by itsmrwave** [comment]
@FooBarWidget At what point are these variables cleared? Does the order matter? That is ... where we are supposed to place ...

```
COPY nginx-env.conf /etc/nginx/main.d/rails-env.conf
```

... in the Dockerfile? I've tried placing that line before end after the init and enable Nginx/Passenger sections and when I run `RUN printenv` in an attempt to debug I just get ...

```
HOSTNAME=dd360632d03c
HOME=/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/app/webapp
```

By the way I'm on Elastic Beanstalk ... it could be that AWS's EB is not passing the variables (which I doubt because their docs say it does).

**Comment by FooBarWidget** [comment]
> At what point are these variables cleared?

During Nginx startup.

>  Does the order matter?

No.

> and when I run RUN printenv in an attempt to debug I just get

`RUN printenv` doesn't display the environment variables. If you place `RUN printenv`, it simply prints the environment variables that are set during `docker build` time. That has got nothing to do with the environment variables that are active during container run time.

rails-env.conf also doesn't set any environment variables outside Nginx, so you won't be able to see them in the shell.

**Comment by itsmrwave** [comment]
@FooBarWidget Thanks!!! :+1: I've posted up my full config up on StackOverflow ... I figure it'll be helpful for the specific use case of Passenger-Docker + Rails + Elastic Beanstalk. However it's not for a multiple container docker config but a single container  docker config.

Link: http://stackoverflow.com/a/31516528/2184155
