### ISSUE TITLE
phusion/passenger-full seems missing

### ISSUE THREAD

**Issue by andreicristianpetcu** [phusion/passenger-docker#94]
Hello, 

I have an old Dockerfile which worked some time ago, I tried to build it again and it fails. Check out this output:

Sending build context to Docker daemon 1.161 MB
Sending build context to Docker daemon 
Step 0 : FROM phusion/passenger-full
Trying to pull repository docker.io/phusion/passenger-full ... failed
INFO[0000] Get https://index.docker.io/v1/repositories/phusion/passenger-full/images: dial tcp: lookup index.docker.io: No address associated with hostname 

You can see the Dockerfile [here](https://github.com/andreicristianpetcu/tribunal/blob/0e99ea61d0e99e3b8fa0635a5e57472bc0ff752c/Dockerfile)

I also tried removing the version.

Thank you

**Comment by FooBarWidget** [comment]
That is a network error on your server, not a problem with passenger-docker. Your server was unable to contact the Docker registry server.
