### ISSUE TITLE
Set nginx passenger configuration values via environment

### ISSUE THREAD

**Issue by bkeroackdsc** [phusion/passenger-docker#95]
Hi,

Similar to the solution implemented for `passenger_app_env` (see #28), it would be very helpful to have environmental variables implemented for other Passenger configuration values. For example, `passenger_min_instances`/`passenger_max_instances` (since these values will vary between staging/testing and production), `passenger_friendly_error_pages` (again, testing vs production), `passenger_rolling_restarts`, etc.

Essentially all of these configuration values must be hard-coded in the nginx config so the only way to toggle them on a per-environment basis is to use some kind of sed hack. It would be great is they could be set thusly:

``` bash
$ docker run -d -e PASSENGER_MIN_INSTANCES=1 -e PASSENGER_MAX_INSTANCES=1 -e PASSENGER_APP_ENV=development acme/my-container-image:latest /sbin/my_init
```

**Comment by ain** [comment]
Also it seems to me all environment variables defined by compose YAML  render useless as Passenger rewrites the ENV completely?

**Comment by OnixGH** [comment]
This is possible since 5.0.22: https://github.com/phusion/passenger/issues/1661
