### ISSUE TITLE
Apache suppoer

### ISSUE THREAD

**Issue by meekrosoft** [phusion/passenger-docker#98]

**Comment by FooBarWidget** [comment]
Sorry, supporting Apache is not something we plan on doing with passenger-docker. We encourage you to build your own image if you need Apache.

**Comment by meekrosoft** [comment]
I understand, but do you have any advice for doing this?  Or should I port to nginx?

**Comment by FooBarWidget** [comment]
Do you have specific reasons why you need Apache? Do you require a specific Apache module or specific Apache features? If not, then I recommend using Nginx.

**Comment by meekrosoft** [comment]
Not really, just the usual SSH etc.  I didn't set up the site so I don't know the historical reasons for the choice, but I guess they were just following this tutorial:
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-passenger-and-apache-on-ubuntu-14-04
