### ISSUE TITLE
Jruby 9000 support

### ISSUE THREAD

**Issue by mattclar** [phusion/passenger-docker#99]
I noticed that Phusion Passenger has been upgraded to support jruby9000. Thoughgt I would open an issue here to see if that could be added to the docker image!

**Comment by FooBarWidget** [comment]
Yes, I will plan it for the next release.

**Comment by chareice** [comment]
大概啥时候完成 😄我要买企业版

**Comment by FooBarWidget** [comment]
@chareice A release is coming up. If everything goes well, it will be done today. :)
